prod_snapshot_2015-09-24_1030/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <label>Partner Type</label>
        <picklist>
            <picklistValues>
                <fullName>USCP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>PartnerMarket</fullName>
        <active>true</active>
        <description>Other News Orgs</description>
        <label>Partner Market</label>
    </recordTypes>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Affiliated</fullName>
        <active>true</active>
        <description>Contacts That Are Associated With Gannett Properties (Sales Reps) But Do Not Have A GL SF Login</description>
        <label>Affiliated</label>
    </recordTypes>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Call_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Call Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Connected_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Connected Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Gannett_Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gannett Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>AL, Greensboro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL, Montgomery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR, Little Rock</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asbury Park, NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asheville, NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atlanta, GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ, Phoenix</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangor, ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Binghamton, NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buffalo, NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burlington, VT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA, Palm Springs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA, Sacramento</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA, Salinas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Jersey, NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Minnesota, MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Ohio, MNCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Wisconsin, WI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cincinnati, OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cleveland, OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO, Denver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO, Fort Collins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO, Northern Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Columbia, NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC, Washington</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE, Delaware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE, Wilmington</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denver, CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Des Moines, IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Detroit, MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA, Des Moines</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Marketing_Source__c</fullName>
        <label>Marketing Source</label>
        <picklist>
            <picklistValues>
                <fullName>USCP Channel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BC Channel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Road Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seminars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Related_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Media Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sponsored Leads</relationshipLabel>
        <relationshipName>RelatedLeads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesRep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Affl Sales Rep</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sponsored Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Digital_Fulfillment</fullName>
        <active>true</active>
        <businessProcess>Market Login</businessProcess>
        <label>Digital Fulfillment</label>
    </recordTypes>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Active_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active CP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Active_DC__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active DC</label>
        <type>Checkbox</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/beforeUpdateOnLead_tstclass.cls
// CC Ph2 - "myUnitTest" and "myUnitTest2" aren't descriptive

/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */

@isTest
private class beforeUpdateOnLead_tstclass {
	
	// <refactor> use more clear testMethod names
    static testMethod void testLeadUpdateTrigger1() {
        // <refactor> test data creation should be done using a data creation class
        Lead testLead = new Lead(LastName = 'WingateTest', Company = 'WingateWorks', Status = 'Uncontacted - New');
        insert testLead;        
		
		Lead testLeadAfter = [SELECT Id, Connected_Count__c, Call_Count__c, Lead_Owner__c
							  FROM Lead
							  WHERE Id = :testLead.Id];
		// <refactor> nothing being asserted or tested 
		
		//System.assertEquals('005A0000001WlbjIAC', testLeadAfter.Lead_Owner__c);
		        
    }
    // <refactor> use more clear testMethod names
    static testMethod void testLeadUpdateTrigger2() {
        // <comment> is this comment helpful ? 
        
        // <PWP> 003F000000on3GD = Shane Morris - A sales rep for the Des Moines Register, i.e. an affiliate.
        // The Before Update Lead trigger depends on this contact record, but I refuse to make a constant out of
        // a real person - as real people are rarely constant. I'll create a Test Contact with the same 
        // attributes as Shane, instead, Then recreate the lead below
        // </PWP>
        //Lead testLead2 = new Lead(SalesRep__c = '003F000000on3GD',
        //						  Company = 'TestDigitialFulf',
        //						  Status = 'Awaiting Assignment',
        //						  RecordTypeId = RecordTypeCache.getRecordType('Lead', 'Digital_Fulfillment').Id,
        //						  LastName = 'TestFirstName TestLastName');
        //insert testLead2;  
        
        // Create a Partner Market Account for the Affiliate SalesRep
        List<Account> affiliateAccount = TestData_Account.createAccounts(1);
        affiliateAccount[0].RecordTypeId = RecordTypeCache.getRecordType('Account', 'PartnerMarket').Id;
        affiliateAccount[0].Partner_Type__c = 'USCP';
        insert affiliateAccount[0];
        
        Market__c testMarket = new Market__c(Name = 'IA, Des Moines', Active_DC__c = true, Active_CP__c = true);
        insert testMarket;
        
        List<Contact> affiliateSalesReps = TestData_Contact.createContacts('Chuck', 'Norris', 1);
        affiliateSalesReps[0].RecordTypeId = RecordTypeCache.getRecordType('Contact', 'Affiliated').Id;
        affiliateSalesReps[0].Market__c = testMarket.Id;
        affiliateSalesReps[0].OwnerId = Constants.GANNETT_LOCAL_USER.id;
        affiliateSalesReps[0].AccountId = affiliateAccount[0].Id;
        insert affiliateSalesReps[0];
        
        List<Lead> affiliateLeads = TestData_Lead.createLeads('TestFirstName', 'TestLastName', 'TestDigitialFulf', 1);
        affiliateLeads[0].SalesRep__c = affiliateSalesReps[0].Id;
        affiliateLeads[0].Status = 'Awaiting Assignment';
        affiliateLeads[0].RecordTypeId = RecordTypeCache.getRecordType('Lead', 'Digital_Fulfillment').Id;
        insert affiliateLeads[0];  
  
		Lead testLeadAfter = [SELECT Id, Related_Company__c, Gannett_Market__c, Marketing_Source__c
							  FROM Lead
							  WHERE Id = :affiliateLeads[0].Id];
		// <refactor> use Test.startTest(); Test.stopTest(); to reset limits 
		// <refactor> needs an errror message to describe the problem
		System.assertEquals(affiliateAccount[0].Id, testLeadAfter.Related_Company__c);
		System.assertEquals(testMarket.Id, testLeadAfter.Gannett_Market__c);  
		System.assertEquals('USCP Channel', testLeadAfter.Marketing_Source__c);     
    }
}