prod_snapshot_2015-09-24_1030/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Affl_Sales_Rep__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Affl Sales Rep</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Affl Accounts</relationshipLabel>
        <relationshipName>Affl_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Dig_Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dig - Account Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>USCP_Opportunity</fullName>
        <active>true</active>
        <businessProcess>USCP Opportunity Process</businessProcess>
        <description>USCP Opportunity</description>
        <label>USCP Opportunity</label>
    </recordTypes>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Affl_Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Affl Sales Rep</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Affiliated_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dig_Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dig Account Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Dig_AM_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Acct_Id__c</fullName>
        <formula>Opportunity.AccountId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opp Acct Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opp_Affl_Sales_Rep__c</fullName>
        <formula>Opportunity.Sales_Rep__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opp Affl Sales Rep</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opp_Dig_Acct_Man_Id__c</fullName>
        <formula>Opportunity.Dig_Account_Manager__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opp Dig Acct Man Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opp_Owner_Id__c</fullName>
        <formula>Opportunity.OwnerId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opp Owner Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opp_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Rep_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Qty_ContractMonths__c</fullName>
        <label>Number of Contract Months</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <description>Opportunity Record type Name</description>
        <label>Record Type Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Waiting_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Onboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting On Client Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting On Client Resource</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hard Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Non-Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled-Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>--Internal Use Only--</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused:Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused:No Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/OpportunityLineItemBeforeInsertHandler.cls
/**
 *  @Class Name   : OpportunityLineItemBeforeInsertHandler
    Created By    : Praneeth Kaleru
    Descritpion   : To handler the Opportunity Line item before insert operations
    Modifications : 03/04/2015 Refactored 
 */
public class OpportunityLineItemBeforeInsertHandler extends TriggerHandlerBase {
     
    public override void mainEntry(TriggerParameters tp) {
        this.setOpportunityLineItemFieldsBeforeInsert(tp.newList);
        setRecordTypeFlag(tp.newList);
    }
    
    public override void inProgressEntry(TriggerParameters tp) {
        
    }
    
    /* 
                    ----------- BEGIN CODE TRANSPLANT -----------------
    */
    //set Opportunity Fields before insert based on other field data
    private void setOpportunityLineItemFieldsBeforeInsert(List<OpportunityLineItem> newOpportunityLineItems) {
    	//Getting Opportunity RecordType Id 
    	Set<Id> oppIds = new Set<Id>();
    	for(OpportunityLineItem oneOppLineItem : newOpportunityLineItems){
    		oppIds.add(oneOppLineItem.OpportunityId);
    	}
    	
    	Map<Id, Opportunity> mapOpportunities = new Map<Id, Opportunity>(
    												[Select Id, RecordTypeId from Opportunity Where Id IN: oppIds]
    											);
    	//Getting Opportunity RecordType Id 
    	
        if(UserInfo.GetUserId() != Constants.GANNETT_LOCAL_USER.Id ){//compare the two to check for gl account and skip if so
            for(OpportunityLineItem oneOppLineItem : newOpportunityLineItems){
                oneOppLineItem.Opp_Owner__c             =   oneOppLineItem.Opp_Owner_Id__c;
                oneOppLineItem.Dig_Account_Manager__c   =   oneOppLineItem.Opp_Dig_Acct_Man_Id__c;
                oneOppLineItem.Affl_Sales_Rep__c        =   oneOppLineItem.Opp_Affl_Sales_Rep__c;
                oneOppLineItem.Account__c               =   oneOppLineItem.Opp_Acct_Id__c;
                System.debug('Opportunity RecordTypeId from OLI Trigger >> ' + oneOppLineItem.Opportunity.RecordTypeId);
                if((oneOppLineItem.Waiting_Status__c == '' || oneOppLineItem.Waiting_Status__c == Null) 
                    && oneOppLineItem.Opp_Dig_Acct_Man_Id__c != Null
                    && mapOpportunities.get(oneOppLineItem.OpportunityId).RecordTypeId != RecordTypeCache.getRecordType('Opportunity', 'USCP_Opportunity').Id){
                    oneOppLineItem.Waiting_Status__c='Awaiting Onboard';
                }
				if(mapOpportunities.get(oneOppLineItem .OpportunityId).RecordTypeId  == RecordTypeCache.getRecordType('Opportunity', 'USCP_Opportunity').Id){
                oneOppLineItem.Quantity = oneOppLineItem.Qty_ContractMonths__c;
				}
            }
        }
       
    }
    
    private void setRecordTypeFlag(List<OpportunityLineItem> newOpportunityLineItems)
    {
         Map<Id,RecordType> recMap = new Map<id,RecordType>([SELECT id,Name from RecordType where SobjectType = 'Opportunity']);
       
        Set<id> oppIdLst = new Set<id>();
        for(OpportunityLineItem oneOppLineItem : newOpportunityLineItems)
           oppIdLst.add(oneOppLineItem.opportunityid);
        Map<id,Opportunity> oppMap = new Map<id,Opportunity>([select id,recordTypeid from opportunity where id =: oppIdLst]);
        for(OpportunityLineItem oneOppLineItem : newOpportunityLineItems)
        {
           Opportunity opp = oppMap.get(oneOppLineItem.opportunityid);
           if(recMap != null && opp.recordTypeid != null) 
           oneOppLineItem.Record_Type_Name__c = recMap.get(opp.recordTypeid).name;
            
          /* if(opp.recordTypeid == rec.id)
             oneOppLineItem.Record_Type_Name__c = '0';
           else
             oneOppLineItem.Record_Type_Name__c = '1';  */
        }
        
    }
}