prod_snapshot_2015-09-24_1030/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Affl_Sales_Rep__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Affl Sales Rep</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Affl Accounts</relationshipLabel>
        <relationshipName>Affl_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Affl_Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Affl Sales Rep</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Phone__c</fullName>
        <label>Company Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Monthly_Spend__c</fullName>
        <label>Acct Tot Mthly Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Notify_Email_1__c</fullName>
        <label>Notify Email 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>PPC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facebook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Targeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maps/Reputation Dashboard</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Notify_Email_1__c</fullName>
        <label>Notify Email 1</label>
        <type>Email</type>
    </fields>
    <recordTypes>
        <fullName>SML_Opportunity</fullName>
        <active>true</active>
        <businessProcess>Acquisition</businessProcess>
        <label>SML Opportunity</label>
    </recordTypes>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/afteronCase_Class.cls
//CC Ph2 Test Class - not only not named to identify it as such, but actually has "Class" in it's name
// Rename Test Methods to be meaningful

@isTest
private class afteronCase_Class {
	static testMethod void testAfterCaseTrigger() {
    	// For seeAllData=False (API 24+), need to load the constants data in the test DB
    	Constants.loadData();
		
		// <refactor> test data creation utility should be used to create test data 
		Account a = new Account();
        a.Name = 'Test Account';
        insert a;
        
        // <refactor> test data creation utility should be used to create test data 
        Opportunity o1 = new Opportunity();
        o1.AccountId = a.Id;
        o1.Name = 'Test Opp 1';
        o1.StageName = 'Booked Appointment';
        o1.CloseDate = date.today().addDays(2);
        o1.RecordTypeId = RecordTypeCache.getRecordType('Opportunity', 'SML_Opportunity').Id;
        insert o1;
        
        // <refactor> test data creation utility should be used to create test data 
        Case c1 = new Case();
        c1.Affl_Sales_Rep__c = Constants.NOT_IN_LIST_CONTACT.id;
        c1.Subject = 'Test1Subject';
        c1.Company_Name__c = 'Test1CompanyName';
        c1.Contact_Name__c = 'Test1ContactName';
        c1.Contact_Phone__c = '(402) 968-9779';
        c1.Product__c = 'PPC;SEO';
        c1.Monthly_Spend__c = 5000;
        c1.Description = 'Test1Description';
        c1.Notify_Email_1__c = 'bobtest@test.com'; // <refactor> could use constants 
        
        insert c1;
        
        // <refactor> use Test.startTest; test.stopTest to reset limits on specific blocks of code
        c1.Opportunity__c = o1.Id;
        update c1;
        
        Opportunity testOppAfter = [SELECT Id, Notify_Email_1__c FROM Opportunity WHERE Id = :o1.Id];
        // <refactor> needs an errror message to describe the problem
        system.assertequals('bobtest@test.com',testOppAfter.Notify_Email_1__c);
        
	}
}