prod_snapshot_2015-09-24_1030/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Expected_Prod_Mix__c</fullName>
        <label>Expected Prod Mix</label>
        <picklist>
            <picklistValues>
                <fullName>01:Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02:Facebook Ads</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03:Maps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04:PPC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05:Retargeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06:SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07:Social Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08:Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09:Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>W_Keyword_01__c</fullName>
        <label>W Keyword 01</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>W_Keyword_02__c</fullName>
        <label>W Keyword 02</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>W_Keyword_03__c</fullName>
        <label>W Keyword 03</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>W_Keyword_04__c</fullName>
        <label>W Keyword 04</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>W_Keyword_05__c</fullName>
        <label>W Keyword 05</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>W_Keyword_06__c</fullName>
        <label>W Keyword 06</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>W_Keyword_07__c</fullName>
        <label>W Keyword 07</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>W_Keyword_08__c</fullName>
        <label>W Keyword 08</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>W_Keyword_09__c</fullName>
        <label>W Keyword 09</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>W_Keyword_10__c</fullName>
        <label>W Keyword 10</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>GL_Digital_Audit</fullName>
        <active>true</active>
        <businessProcess>GL Digital Audit</businessProcess>
        <label>GL Digital Audit</label>
    </recordTypes>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/test_whooshHandler.cls
//<PWP> No Tests of functionality

@isTest
private class test_whooshHandler {

	// <refactor> use better testmethod names for clarity 
    static testMethod void myUnitTest() {
    	
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('JSONWhooshResponse');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, mock);
        
        // <comment>
        /*** <PWP> Good effort on the RecordType matching, but mine (RecordTypeCache) is better ;-) Delete once verified
        //Replace the word contact with whichever object you would like to find the record type ID for.
		Map <String,Schema.RecordTypeInfo> recordTypes = Case.sObjectType.getDescribe().getRecordTypeInfosByName();

 		//Get the record type ID of from the Map based on the Name, replace RecordTypeString with whatever the record type's name is 
		ID recTypeId = recordTypes.get('GL Digital Audit').getRecordTypeId();
		</PWP>***/
		
		RecordType rtCaseDigAudit = RecordTypeCache.getRecordType('Case', 'GL_Digital_Audit');
	
		// <refactor> test data creation utility should be used to create test data 
        Case c = new Case();
        c.RecordTypeId = rtCaseDigAudit.Id;
        c.Expected_Prod_Mix__c = 'Social Media';
        c.Status = 'Requested';
        c.W_Keyword_01__c = 'Test';
        c.W_Keyword_02__c = 'Test';
        c.W_Keyword_03__c = 'Test';
        c.W_Keyword_04__c = 'Test';
        c.W_Keyword_05__c = 'Test';
        c.W_Keyword_06__c = 'Test';
        c.W_Keyword_07__c = 'Test';
        c.W_Keyword_08__c = 'Test';
        c.W_Keyword_09__c = 'Test';
        c.W_Keyword_10__c = 'Test';
        insert c;
        
        test.startTest();
        	whooshHandler rh = new whooshHandler();
        	whooshHandler.updateWhooshResults(c.ID);
        test.stopTest();
        
        // <refactor> no assertions 
        //system.debug('RESPONSE BODY: ' + resp.getBody());
        
    }
}