prod_snapshot_2015-09-24_1030/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Affl_Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Affl Sales Rep</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Phone__c</fullName>
        <label>Company Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Digital_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Digital Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>DigitalRequests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Monthly_Spend__c</fullName>
        <label>Acct Tot Mthly Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>PPC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facebook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Targeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maps/Reputation Dashboard</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Lead.object
<CustomObject>
    <recordTypes>
        <fullName>SML_Lead</fullName>
        <active>true</active>
        <businessProcess>SML Lead Process</businessProcess>
        <label>SML Lead</label>
    </recordTypes>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Survey_Results__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup relationship with contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Results</relationshipLabel>
        <relationshipName>Survey_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Results</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Survey Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/TestleadSurveyTrigger.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */

@isTest
private class TestleadSurveyTrigger {

    static testMethod void testLeadInsert() {
        
        // <refactor> test data creation utility should be used to create test data 
        Lead nLead = new Lead();
        nLead.LastName = 'test lead';
        nLead.RecordTypeId = RecordTypeCache.getRecordType('Lead', 'SML_Lead').Id;
        nLead.Company = 'test';
        nLead.Email = 'test.email@gannett.com';
        nLead.Street = '123 W Test Dr';
        nLead.City = 'Phoenix';
        nLead.PostalCode = '85016';
        nLead.State = 'AZ';
        nLead.Country = 'United States';
        insert nLead;
        
        // <refactor> test data creation utility should be used to create test data 
        Case case1 = new Case();
        case1.Affl_Sales_Rep__c = Constants.NOT_IN_LIST_CONTACT.id;
        case1.Subject = 'Test1Subject';
        case1.Company_Name__c = 'Test1CompanyName';
        case1.Contact_Name__c = 'Test1ContactName';
        case1.Contact_Phone__c = '(402) 968-9779';
        case1.Product__c = 'PPC;SEO';
        case1.Monthly_Spend__c = 5000;
        case1.Description = 'Test1Description';
        case1.Digital_Lead__c = nLead.Id;
        insert case1;
         
         // <refactor> use Test.startTest; test.stopTest to reset limits on specific blocks of code
         Database.Leadconvert convrtLd =new Database.Leadconvert ();
         convrtLd.setLeadId(nLead.Id);
         convrtLd.setConvertedStatus('Sales Qualified (SQL)');
         Database.Leadconvertresult lcRes = Database.convertLead(convrtLd, true);
         
         Id accountId = lcRes.getAccountId(); 
         
         // <refactor> needs an errror message to describe the problem
         System.assertEquals(accountId, [Select AccountId From Case Where Id =: case1.Id].AccountId );
         //System.assertEquals(contactId, [Select Contact__c From Survey_Results__c Where Id =: sr2.Id].Contact__c );
    }
}