prod_snapshot_2015-09-24_1030/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Promotion_Source__c</fullName>
        <label>Promotion Source</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Campaign__c</fullName>
        <label>Target Campaign</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Industry_AffiliatedMarkets__c</fullName>
        <inlineHelpText>Help Text</inlineHelpText>
        <label>Industry General</label>
        <picklist>
            <picklistValues>
                <fullName>Automotive Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employment Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospitality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Real Estate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Repair Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales/Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Security Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Promotion_Source__c</fullName>
        <label>Promotion Source</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Campaign__c</fullName>
        <label>Target Campaign</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/PopulateCampaignMemberFields.cls
@isTest(SeeAllData=true)
Private Class PopulateCampaignMemberFields{
    static testmethod void populateCampaignMemberTestMethod(){ 
    
        //Insert Account
        Account acc = new Account(name='testAccountG');
        insert acc;
        
        //Insert Campaign
        Campaign c1 = new Campaign(name='testCampaign');
        insert c1;
        Campaign c2 = new Campaign(name='testCampaignG');
        insert c2;
        
        //Insert Contact
        Contact con = new Contact(accountid=acc.id,lastname='testlastname',Target_Campaign__c=c1.id);
        insert con;
        
        //Insert Lead
        Lead led = new Lead(firstname='testGLead',lastname='testlastname',Company='testGCompany',Industry_AffiliatedMarkets__c='Education',Target_Campaign__c=c1.id);
        insert led;
        
        //Update Lead with Target and Promotion Id
        led.Promotion_Source__c = c2.id;
        update led;
        
        //Update Contact with Target and Promotion Id
        con.Promotion_Source__c = c2.id;
        update con;
        
        //Insert Lead with all the data
        Lead ledd = new Lead(firstname='testingLead',lastname='testingname',Company='testingCompany',Industry_AffiliatedMarkets__c='Education',Target_Campaign__c=c1.id,Promotion_Source__c=c2.id);
        insert ledd;
        //Insert Contact with all the data
        Contact cont = new Contact(accountid=acc.id,lastname='testlastname',Target_Campaign__c=c1.id,Promotion_Source__c=c2.id);
        insert cont;
    }
    
}