prod_snapshot_2015-09-24_1030/objects/Invoice_LineItem__c.object
<CustomObject>
    <description>Maintains all Invoice records which can be used for billing .</description>
    <fields>
        <fullName>Invoice_PeriodEnd__c</fullName>
        <label>Period End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_PeriodStart__c</fullName>
        <label>Period Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OpportunityRef__c</fullName>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectRef__c</fullName>
        <label>Related Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TotalMonthlyCharge__c</fullName>
        <label>Total Monthly Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>isDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Locked</label>
        <type>Checkbox</type>
    </fields>
    <label>ILI</label>
    <nameField>
        <displayFormat>ILI-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>CanCreateILI__c</fullName>
        <formula>Text(Waiting_Status__c) == PricebookEntry.Product2.Invoice_StatusToCreateILI__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Can Create ILI&apos;s</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cancellation_Category__c</fullName>
        <label>Cancellation Category</label>
        <picklist>
            <picklistValues>
                <fullName>Cancelled Before Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled After Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Non-Renewal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cancellation_Reason__c</fullName>
        <label>Cancellation Reason</label>
        <picklist>
            <controllingField>Cancellation_Category__c</controllingField>
            <picklistValues>
                <fullName>Sales Expectation Mismatch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G/O Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Business Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Unresponsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reallocation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Non Renewal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Has_ILI__c</fullName>
        <formula>Project__r.Has_ILI__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Has ILI&apos;S</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_CancelDate__c</fullName>
        <label>Invoice Cancel Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_ServiceStartDate__c</fullName>
        <label>Product Start of Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Id__c</fullName>
        <formula>PricebookEntry.Product2.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Qty_ContractMonths__c</fullName>
        <label>Number of Contract Months</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalMonthlyCharge__c</fullName>
        <formula>UnitPrice  + (UnitPrice  *  Mgmt_Fee_Percent__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Monthly Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Waiting_Status_Descr__c</fullName>
        <label>Status Descr/Notes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Waiting_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Onboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting On Client Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting On Client Resource</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hard Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Non-Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled-Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>--Internal Use Only--</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused:Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused:No Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Invoice_Frequency__c</fullName>
        <description>USCP Custom Field: Invoice Frequency</description>
        <label>Invoice Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Two Times</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Invoice_StatusToCreateILI__c</fullName>
        <label>Status to Create ILIs</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>CanCreateILI__c</fullName>
        <formula>Project_Status__c== Related_Product__r.Invoice_StatusToCreateILI__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Can Create ILI&apos;s</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cancellation_Category__c</fullName>
        <label>Cancellation Category</label>
        <picklist>
            <picklistValues>
                <fullName>Cancelled Before Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled After Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Non-Renewal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cancellation_Reason__c</fullName>
        <label>Cancellation Reason</label>
        <picklist>
            <controllingField>Cancellation_Category__c</controllingField>
            <picklistValues>
                <fullName>Sales Expectation Mismatch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G/O Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Business Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Unresponsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reallocation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Non Renewal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_ILI__c</fullName>
        <formula>Count_Of_ILI__c  &gt;= 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Has ILI&apos;S</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_CancelDate__c</fullName>
        <label>Invoice Cancel Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_ServiceStartDate__c</fullName>
        <label>Product Start of Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Id__c</fullName>
        <label>Product Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qty_ContractMonths__c</fullName>
        <label>Qty Contract Months</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalMonthlyCharge__c</fullName>
        <description>OLI total Monthly Charge Amount</description>
        <label>Total Monthly Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Updates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/USCPILIGenerator_Test.cls
@isTest(SeeAllData=True)
private class USCPILIGenerator_Test {

    static testMethod void insertInvoiceLineItems_Test() {
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opportunity';
        opp.CloseDate = date.today();
        opp.StageName = 'Closed Won';
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('USCP Opportunity').getRecordTypeId();
        
        insert opp;
        
        PriceBook2 pb2Standard = [select Id from Pricebook2 where isStandard=true];
        
        PriceBook2 pb2USCP = [select Id from Pricebook2 where Name = 'USCP Wholesale Price Book'];
        
        Product2 p2 = new Product2(Name='Test Product',isActive=true, Invoice_StatusToCreateILI__c = 'Live');
        insert p2;
        
        PricebookEntry pbe = new PricebookEntry(Pricebook2Id=pb2Standard.Id, Product2Id=p2.Id, UnitPrice=2000, isActive=true);
        insert pbe;
        
        PricebookEntry pbeUSCP = new PricebookEntry(Pricebook2Id=pb2USCP .Id, Product2Id=p2.Id, UnitPrice=2000, isActive=true);
        insert pbeUSCP;
        
        list<OpportunityLineItem> olilist = new  list<OpportunityLineItem>();
        OpportunityLineItem oli = new OpportunityLineItem();
        oli.Quantity=2;
        oli.TotalPrice = 2000;
        oli.ServiceDate = date.today();
        oli.OpportunityId = opp.Id;
        oli.PriceBookEntryId=pbeUSCP.Id;
        oli.Waiting_Status__c = 'Live1';
        oli.Invoice_ServiceStartDate__c = date.today().adddays(2);
        oli.Qty_ContractMonths__c = 2;
        
        
        olilist.add(oli);
        
        insert olilist;
        
        Project__c proj = [SELECT Id,Product_Id__c,Has_ILI__c, CanCreateILI__c,Qty_ContractMonths__c , Invoice_ServiceStartDate__c, Project_Status__c  FROM Project__c WHERE Product_Id__c =: oliList[0].Id];
        //proj.Qty_ContractMonths__c = 5;
        proj.Project_Status__c = 'Live';
        proj.Invoice_ServiceStartDate__c = date.today().adddays(2);
        update proj;
        system.debug('*****mydebug*********'+proj+'*****'+proj.Invoice_ServiceStartDate__c);
        //update proj;
        
        /*USCPILIGenerator classObj = new USCPILIGenerator();
        map<Id, Id> oliWithProjId = new map<Id, Id>();
        oliWithProjId.put(proj.Product_Id__c, proj.Id);
        classObj.insertInvoiceLineItems(oliWithProjId);
        *///classObj.updateInvoiceLineItems(2, date.today(), 2000, opp.Id, proj.Id);    
        //proj.Cancelled__c = true;
        //update proj;
        //classObj.cancelInvoiceLineItems(new set<Id>{proj.Id});
        
        list<Invoice_LineItem__c> iliList = new list<Invoice_LineItem__c>();
        iliList = [SELECT Id, Invoice_PeriodStart__c, OpportunityRef__c, 
                        ProjectRef__c, TotalMonthlyCharge__c, isLocked__c,
                        isDeleted__c, Invoice_PeriodEnd__c
                 FROM Invoice_LineItem__c
                 WHERE OpportunityRef__c=: opp.Id
                     ];
                     
        system.assertEquals(iliList.size(), 2);
        
        /*test.startTest();
        proj.Invoice_CancelDate__c = date.today().adddays(2);
        proj.Project_Status__c  = 'Cancelled';
        update proj;
        Test.stopTest();*/
    }
    
    static testMethod void insertInvoiceLineItems_Test_2() {
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opportunity';
        opp.CloseDate = date.today();
        opp.StageName = 'Closed Won';
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('USCP Opportunity').getRecordTypeId();
        
        insert opp;
        
        PriceBook2 pb2Standard = [select Id from Pricebook2 where isStandard=true];
        
        PriceBook2 pb2USCP = [select Id from Pricebook2 where Name = 'USCP Wholesale Price Book'];
        
        Product2 p2 = new Product2(Name='Test Product',isActive=true, Invoice_Frequency__c= 'Two Times', Invoice_StatusToCreateILI__c = 'Live');
        insert p2;
        
        PricebookEntry pbe = new PricebookEntry(Pricebook2Id=pb2Standard.Id, Product2Id=p2.Id, UnitPrice=2000, isActive=true);
        insert pbe;
        
        PricebookEntry pbeUSCP = new PricebookEntry(Pricebook2Id=pb2USCP .Id, Product2Id=p2.Id, UnitPrice=2000, isActive=true);
        insert pbeUSCP;
        
        list<OpportunityLineItem> olilist = new  list<OpportunityLineItem>();
        OpportunityLineItem oli = new OpportunityLineItem();
        oli.Quantity=2;
        oli.TotalPrice = 2000;
        oli.ServiceDate = date.today();
        oli.OpportunityId = opp.Id;
        oli.PriceBookEntryId=pbeUSCP.Id;
        oli.Waiting_Status__c = 'Live1';
        oli.Invoice_ServiceStartDate__c = date.today().adddays(2);
        oli.Qty_ContractMonths__c = 2;
        
        
        olilist.add(oli);
        
        insert olilist;
        
        Project__c proj = [SELECT Id,Product_Id__c,Has_ILI__c, CanCreateILI__c,Qty_ContractMonths__c , Invoice_ServiceStartDate__c, Project_Status__c  FROM Project__c WHERE Product_Id__c =: oliList[0].Id];
        proj.Project_Status__c = 'Live';
        proj.Invoice_ServiceStartDate__c = date.today().adddays(2);
        update proj;
        system.debug('*****mydebug*********'+proj+'*****'+proj.Invoice_ServiceStartDate__c);
        
        list<Invoice_LineItem__c> iliList = new list<Invoice_LineItem__c>();
        iliList = [SELECT Id, Invoice_PeriodStart__c, OpportunityRef__c, 
                        ProjectRef__c, TotalMonthlyCharge__c, isLocked__c,
                        isDeleted__c, Invoice_PeriodEnd__c
                 FROM Invoice_LineItem__c
                 WHERE OpportunityRef__c=: opp.Id
                     ];
                     
        system.assertEquals(iliList.size(), 2);
    }
    
    static testMethod void cancelInvoiceLineItems_Test() {
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opportunity';
        opp.CloseDate = date.today();
        opp.StageName = 'Closed Won';
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('USCP Opportunity').getRecordTypeId();
        
        insert opp;
        
        PriceBook2 pb2Standard = [select Id from Pricebook2 where isStandard=true];
        
        PriceBook2 pb2USCP = [select Id from Pricebook2 where Name = 'USCP Wholesale Price Book'];
        
        Product2 p2 = new Product2(Name='Test Product',isActive=true, Invoice_StatusToCreateILI__c = 'Live', Invoice_Frequency__c='One Time');
        insert p2;
        
        PricebookEntry pbe = new PricebookEntry(Pricebook2Id=pb2Standard.Id, Product2Id=p2.Id, UnitPrice=2000, isActive=true);
        insert pbe;
        
        PricebookEntry pbeUSCP = new PricebookEntry(Pricebook2Id=pb2USCP .Id, Product2Id=p2.Id, UnitPrice=2000, isActive=true);
        insert pbeUSCP;
        
        list<OpportunityLineItem> olilist = new  list<OpportunityLineItem>();
        OpportunityLineItem oli = new OpportunityLineItem();
        oli.Quantity=2;
        oli.TotalPrice = 2000;
        oli.ServiceDate = date.today();
        oli.OpportunityId = opp.Id;
        oli.PriceBookEntryId=pbeUSCP.Id;
        oli.Waiting_Status__c = 'Live1';
        oli.Invoice_ServiceStartDate__c = date.today().adddays(2);
        oli.Qty_ContractMonths__c = 2;
        
        
        olilist.add(oli);
        
        insert olilist;
        
        Project__c proj = [SELECT Id,Product_Id__c,Has_ILI__c, CanCreateILI__c,Qty_ContractMonths__c , Invoice_ServiceStartDate__c, Project_Status__c  FROM Project__c WHERE Product_Id__c =: oliList[0].Id];
        //proj.Qty_ContractMonths__c = 5;
        proj.Project_Status__c = 'Live';
        proj.Invoice_ServiceStartDate__c = date.today().adddays(2);
        update proj;
        system.debug('*****mydebug*********'+proj+'*****'+proj.Invoice_ServiceStartDate__c);
        
        list<Invoice_LineItem__c> iliList = new list<Invoice_LineItem__c>();
        iliList = [SELECT Id, Invoice_PeriodStart__c, OpportunityRef__c, 
                        ProjectRef__c, TotalMonthlyCharge__c, isLocked__c,
                        isDeleted__c, Invoice_PeriodEnd__c
                 FROM Invoice_LineItem__c
                 WHERE OpportunityRef__c=: opp.Id
                     ];
                     
        system.assertEquals(iliList.size(), 2);
        
        oli.Waiting_Status__c = 'Cancelled';
        oli.Invoice_ServiceStartDate__c = date.today().adddays(2);
        oli.Invoice_CancelDate__c = date.today().adddays(2);
        oli.Cancellation_Category__c = 'G/O Error';
        oli.Cancellation_Reason__c = 'Test Reason';
        oli.Waiting_Status_Descr__c  = 'Testa Cancel';
        
        update oli;
    }
    
    static testMethod void hardcancelInvoiceLineItems_Test() {
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opportunity';
        opp.CloseDate = date.today();
        opp.StageName = 'Closed Won';
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('USCP Opportunity').getRecordTypeId();
        
        insert opp;
        
        PriceBook2 pb2Standard = [select Id from Pricebook2 where isStandard=true];
        
        PriceBook2 pb2USCP = [select Id from Pricebook2 where Name = 'USCP Wholesale Price Book'];
        
        Product2 p2 = new Product2(Name='Test Product',isActive=true, Invoice_StatusToCreateILI__c = 'Live', Invoice_Frequency__c='One Time');
        insert p2;
        
        PricebookEntry pbe = new PricebookEntry(Pricebook2Id=pb2Standard.Id, Product2Id=p2.Id, UnitPrice=2000, isActive=true);
        insert pbe;
        
        PricebookEntry pbeUSCP = new PricebookEntry(Pricebook2Id=pb2USCP .Id, Product2Id=p2.Id, UnitPrice=2000, isActive=true);
        insert pbeUSCP;
        
        list<OpportunityLineItem> olilist = new  list<OpportunityLineItem>();
        OpportunityLineItem oli = new OpportunityLineItem();
        oli.Quantity=2;
        oli.TotalPrice = 2000;
        oli.ServiceDate = date.today();
        oli.OpportunityId = opp.Id;
        oli.PriceBookEntryId=pbeUSCP.Id;
        oli.Waiting_Status__c = 'Live1';
        oli.Invoice_ServiceStartDate__c = date.today().adddays(2);
        oli.Qty_ContractMonths__c = 2;
        
        
        olilist.add(oli);
        
        insert olilist;
        
        Project__c proj = [SELECT Id,Product_Id__c,Has_ILI__c, CanCreateILI__c,Qty_ContractMonths__c , Invoice_ServiceStartDate__c, Project_Status__c  FROM Project__c WHERE Product_Id__c =: oliList[0].Id];
        //proj.Qty_ContractMonths__c = 5;
        proj.Project_Status__c = 'Live';
        proj.Invoice_ServiceStartDate__c = date.today().adddays(2);
        update proj;
        system.debug('*****mydebug*********'+proj+'*****'+proj.Invoice_ServiceStartDate__c);
        
        list<Invoice_LineItem__c> iliList = new list<Invoice_LineItem__c>();
        iliList = [SELECT Id, Invoice_PeriodStart__c, OpportunityRef__c, 
                        ProjectRef__c, TotalMonthlyCharge__c, isLocked__c,
                        isDeleted__c, Invoice_PeriodEnd__c
                 FROM Invoice_LineItem__c
                 WHERE OpportunityRef__c=: opp.Id
                     ];
                     
        system.assertEquals(iliList.size(), 2);
        
        oli.Waiting_Status__c = 'Hard Cancel';
        oli.Invoice_ServiceStartDate__c = date.today().adddays(2);
        oli.Invoice_CancelDate__c = date.today().adddays(2);
        oli.Cancellation_Category__c = 'G/O Error';
        oli.Cancellation_Reason__c = 'Test Reason';
        oli.Waiting_Status_Descr__c  = 'Test Cancel';
        
        update oli;
    }
    
    static testMethod void updateInvoiceLineItems_Test() {
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opportunity';
        opp.CloseDate = date.today();
        opp.StageName = 'Closed Won';
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('USCP Opportunity').getRecordTypeId();
        
        insert opp;
        
        PriceBook2 pb2Standard = [select Id from Pricebook2 where isStandard=true];
        
        PriceBook2 pb2USCP = [select Id from Pricebook2 where Name = 'USCP Wholesale Price Book'];
        
        Product2 p2 = new Product2(Name='Test Product',isActive=true, Invoice_StatusToCreateILI__c = 'Live', Invoice_Frequency__c='Two Times');
        insert p2;
        
        PricebookEntry pbe = new PricebookEntry(Pricebook2Id=pb2Standard.Id, Product2Id=p2.Id, UnitPrice=2000, isActive=true);
        insert pbe;
        
        PricebookEntry pbeUSCP = new PricebookEntry(Pricebook2Id=pb2USCP .Id, Product2Id=p2.Id, UnitPrice=2000, isActive=true);
        insert pbeUSCP;
        
        list<OpportunityLineItem> olilist = new  list<OpportunityLineItem>();
        OpportunityLineItem oli = new OpportunityLineItem();
        oli.Quantity=2;
        oli.TotalPrice = 2000;
        oli.ServiceDate = date.today();
        oli.OpportunityId = opp.Id;
        oli.PriceBookEntryId=pbeUSCP.Id;
        oli.Waiting_Status__c = 'Fulfilled-Complete';
        oli.Invoice_ServiceStartDate__c = date.today().adddays(2);
        oli.Invoice_CancelDate__c = date.today().adddays(2);
        oli.Cancellation_Category__c = 'G/O Error';
        oli.Cancellation_Reason__c = 'Test Reason';
        oli.Waiting_Status_Descr__c  = 'Test Cancel';
        oli.Qty_ContractMonths__c = 2;
        
        
        olilist.add(oli);
        
        insert olilist;
        
        Project__c proj = [SELECT Id,Product_Id__c,Has_ILI__c, CanCreateILI__c,Qty_ContractMonths__c , Invoice_ServiceStartDate__c, Project_Status__c  FROM Project__c WHERE Product_Id__c =: oliList[0].Id];
        
        Invoice_LineItem__c i = new Invoice_LineItem__c();
        i.OpportunityRef__c = opp.Id;
        i.Invoice_PeriodStart__c = date.today().addmonths(3);
        i.Invoice_PeriodEnd__c = date.today().addmonths(4).adddays(-1);
        i.ProjectRef__c = proj.Id;
        i.TotalMonthlyCharge__c = 200;
        
        insert i;
        
        USCPILIGenerator classObj = new USCPILIGenerator();
        map<id,Id> oliwithproj = new map<id, Id>();
        oliwithproj.put(oli.id,proj.id);
        classObj.updateInvoiceLineItems(oliwithproj);
    }
}