prod_snapshot_2015-09-24_1030/objects/Invoice_LineItem__c.object
<CustomObject>
    <description>Maintains all Invoice records which can be used for billing .</description>
    <fields>
        <fullName>Invoice_LineItemType__c</fullName>
        <label>ILI Type</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kill</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Invoice_PeriodEnd__c</fullName>
        <label>Period End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_PeriodStart__c</fullName>
        <label>Period Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_ScheduleDate__c</fullName>
        <formula>IF( MONTH(Invoice_PeriodStart__c) &lt;&gt; 12 ,
    DATE( YEAR(Invoice_PeriodStart__c) , MONTH(Invoice_PeriodStart__c)+1 ,1),
    DATE( YEAR(Invoice_PeriodStart__c)+1 , 1 ,1))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ILI Schedule Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OpportunityRef__c</fullName>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectRef__c</fullName>
        <label>Related Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TotalMonthlyCharge__c</fullName>
        <label>Total Monthly Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>isDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Deleted</label>
        <type>Checkbox</type>
    </fields>
    <label>ILI</label>
    <nameField>
        <displayFormat>ILI-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/AbstractInvoiceLineItemsClass.cls
public abstract class AbstractInvoiceLineItemsClass
{   
    // creating the  Invoice_Line_Items__c records as per the arguments
    
    public virtual list<Invoice_LineItem__c> createInvoiceLineItems(Integer qtyContractMonths, Date startDate, Decimal oliMonthlyTotal, Id opportunityId, Id projectId){
            
        List<Invoice_LineItem__c> invoiceLineItemList = new List<Invoice_LineItem__c>();
        
        
        for(integer i = 0; i < qtyContractMonths; i++){
            Invoice_LineItem__c invLineItem = new Invoice_LineItem__c();
                invLineItem.Invoice_PeriodStart__c = startDate.addmonths(i);
                invLineItem.Invoice_PeriodEnd__c = startDate.addmonths(i+1).adddays(-1);
                invLineItem.OpportunityRef__c = OpportunityId;
                invLineItem.ProjectRef__c = projectId;
                invLineItem.TotalMonthlyCharge__c = oliMonthlyTotal;
                invLineItem.Invoice_LineItemType__c = 'Standard';
            invoiceLineItemList.add(invLineItem);
        }
            
        return invoiceLineItemList;
    }
    public virtual list<Invoice_LineItem__c> createInvoiceLineItemsForONEProduct(Integer qtyContractMonths, Date startDate, Decimal oliMonthlyTotal, Id opportunityId, Id projectId){
            
        List<Invoice_LineItem__c> invoiceLineItemList = new List<Invoice_LineItem__c>();
       
        
        if(qtyContractMonths!=null && qtyContractMonths>0){
            Invoice_LineItem__c invLineItem = new Invoice_LineItem__c();
                invLineItem.Invoice_PeriodStart__c = startDate;
                invLineItem.Invoice_PeriodEnd__c = startDate.addmonths(1).adddays(-1);
                invLineItem.OpportunityRef__c = OpportunityId;
                invLineItem.ProjectRef__c = projectId;
                invLineItem.TotalMonthlyCharge__c = oliMonthlyTotal;
                invLineItem.Invoice_LineItemType__c = 'Standard';
            invoiceLineItemList.add(invLineItem);
            
            Invoice_LineItem__c invLineItem1 = new Invoice_LineItem__c();
                invLineItem1.Invoice_PeriodStart__c = null;
                invLineItem1.Invoice_PeriodEnd__c = null;
                invLineItem1.OpportunityRef__c = OpportunityId;
                invLineItem1.ProjectRef__c = projectId;
                invLineItem1.TotalMonthlyCharge__c = oliMonthlyTotal;
                invLineItem1.Invoice_LineItemType__c = 'Standard';
            invoiceLineItemList.add(invLineItem1);
        }
            
        return invoiceLineItemList;
    }
    public virtual void insertInvoiceLineItems(List<Invoice_LineItem__c> invoiceLineItemList){
          if(invoiceLineItemList != null && invoiceLineItemList.size()>0){
              system.debug('********invoiceLineItemList**********'+invoiceLineItemList);
            insert invoiceLineItemList;
          }  
    }
    
     // Soft Deleting  Invoice_Line_Items__c records based on like cancel checkbox which in turn calls update on ili's
    public  virtual void deleteInvoiceLineItems(list<Invoice_LineItem__c> invLineItemList){
      for(Invoice_LineItem__c invLineItem : invLineItemList){
            invLineItem.isDeleted__c = true;
            //invLineItem.Invoice_LineItemType__c = 'Cancel'; DEV 3106
        }
        if(invLineItemList!= null && invLineItemList.size() > 0){
             update invLineItemList;
         }
    }
    
    // Updating Invoice LineItems.
    public virtual void updateInvoiceLineItems(list<Invoice_LineItem__c> invLineItemList){
      
        if(invLineItemList!= null && invLineItemList.size() > 0){
             update invLineItemList;
         }
    } 
    
    //Compare Existing ILI List Vs New ILI List and return final ILI List for Regen ILIs
    public  virtual list<Invoice_LineItem__c> regenCreateInvoiceLineItems(list<Invoice_LineItem__c> oldInvLineItemList, 
    													list<Invoice_LineItem__c> newInvLineItemList){
      List<Invoice_LineItem__c> processILIs = new List<Invoice_LineItem__c>();
      //returning back if there are new ILIs 
      if(!(newInvLineItemList!=null && newInvLineItemList.size()>0)){
      	 return processILIs;
      }
      
      Map<Date, Invoice_LineItem__c> newMapILIs = new Map<Date, Invoice_LineItem__c>();
      for(Invoice_LineItem__c  oneILI : newInvLineItemList){
      	 newMapILIs.put((Date)oneILI.Invoice_PeriodStart__c.addMonths(1).toStartofMonth(), oneILI);
      }
      
      System.debug('Map of New ILIs with Date param >> ' + newMapILIs);      
      if(oldInvLineItemList!=null){
	      for(Invoice_LineItem__c  oneILI : oldInvLineItemList){
	      	 System.debug('There are old values here >> ' + (Date)oneILI.Invoice_ScheduleDate__c);
	      	 newMapILIs.remove((Date)oneILI.Invoice_ScheduleDate__c);
	      } 
      }
      processILIs = newMapILIs.values();
      return processILIs;
    } 
}