prod_snapshot_2015-09-24_1030/objects/Invoice_LineItem__c.object
<CustomObject>
    <description>Maintains all Invoice records which can be used for billing .</description>
    <fields>
        <fullName>Invoice_LineItemType__c</fullName>
        <label>ILI Type</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kill</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Invoice_PeriodEnd__c</fullName>
        <label>Period End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_PeriodStart__c</fullName>
        <label>Period Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_ScheduleDate__c</fullName>
        <formula>IF( MONTH(Invoice_PeriodStart__c) &lt;&gt; 12 ,
    DATE( YEAR(Invoice_PeriodStart__c) , MONTH(Invoice_PeriodStart__c)+1 ,1),
    DATE( YEAR(Invoice_PeriodStart__c)+1 , 1 ,1))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ILI Schedule Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Media_Spend__c</fullName>
        <formula>IF(OR(ISPICKVAL(Invoice_LineItemType__c,&apos;Manual&apos;),ISPICKVAL(Invoice_LineItemType__c,&apos;Adjustment&apos;)),null,IF( ProjectRef__r.Related_Product__r.HasMediaSpend__c = true,  Product_Price__c , null))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Media Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OpportunityRef__c</fullName>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectRef__c</fullName>
        <label>Related Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TotalMonthlyCharge__c</fullName>
        <label>Total Monthly Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Wholesale_Fee__c</fullName>
        <formula>IF(OR(ISPICKVAL(Invoice_LineItemType__c,&apos;Manual&apos;),ISPICKVAL(Invoice_LineItemType__c,&apos;Adjustment&apos;)),null,IF( ProjectRef__r.Related_Product__r.HasMediaSpend__c = true ,  TotalMonthlyCharge__c -  Product_Price__c ,  Product_Price__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Wholesale Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>isDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Locked</label>
        <type>Checkbox</type>
    </fields>
    <label>ILI</label>
    <nameField>
        <displayFormat>ILI-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalMonthlyCharge__c</fullName>
        <formula>UnitPrice  + (UnitPrice  *  Mgmt_Fee_Percent__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Monthly Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>TotalMonthlyCharge__c</fullName>
        <description>OLI total Monthly Charge Amount</description>
        <label>Total Monthly Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Updates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/InvoiceLineItemCompCntrl.cls
public class InvoiceLineItemCompCntrl {
    public id oliId {set;get;}
    Public List<Invoice_LineItem__c> invoiceLst; 
  public InvoiceLineItemCompCntrl()
  {
      invoiceLst = new List<Invoice_LineItem__c>();
      
  }
  
   public List<Invoice_LineItem__c>  getInvoiceLst()
  {
      opportunityLineItem oli = [select id,name,opportunity.name,OpportunityId,Product2.Name,LastModifiedBy.Name,Project__c from opportunityLineItem where id =:oliId];
     
      invoiceLst = [select id,name,TotalMonthlyCharge__c,Invoice_LineItemType__c,Invoice_PeriodEnd__c,Invoice_PeriodStart__c,Invoice_ScheduleDate__c,isDeleted__c,isLocked__c,OpportunityRef__c,ProjectRef__c,Wholesale_Fee__c,Media_Spend__c from Invoice_LineItem__c where OpportunityRef__c =:oli.OpportunityId  and ProjectRef__c =:oli.Project__c];
      
      return invoiceLst;
  }  
    
    
}