prod_snapshot_2015-09-24_1030/objects/Invoice_LineItem__c.object
<CustomObject>
    <description>Maintains all Invoice records which can be used for billing .</description>
    <fields>
        <fullName>Invoice_AdjustmentDetails__c</fullName>
        <label>Adjustment Details</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Invoice_CreditOrDebit_Reason__c</fullName>
        <label>Adjustment Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Evergreen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G/O Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Invoice_CreditOrDebit__c</fullName>
        <description>Decides the OLI_Amount__c(Invoice Line Item Total) field to be positive or negative for the ILI&apos;s created manually by clicking on the adjust Invoice button</description>
        <label>Is this an A/R Credit or Debit?</label>
        <picklist>
            <picklistValues>
                <fullName>Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Invoice_LineItemType__c</fullName>
        <label>ILI Type</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kill</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Invoice_PeriodEnd__c</fullName>
        <label>Period End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_PeriodStart__c</fullName>
        <label>Period Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_ScheduleDate__c</fullName>
        <formula>IF( MONTH(Invoice_PeriodStart__c) &lt;&gt; 12 ,
    DATE( YEAR(Invoice_PeriodStart__c) , MONTH(Invoice_PeriodStart__c)+1 ,1),
    DATE( YEAR(Invoice_PeriodStart__c)+1 , 1 ,1))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ILI Schedule Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OpportunityRef__c</fullName>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectRef__c</fullName>
        <label>Related Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TotalMonthlyCharge__c</fullName>
        <label>Total Monthly Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>ILI</label>
    <nameField>
        <displayFormat>ILI-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalMonthlyCharge__c</fullName>
        <formula>UnitPrice  + (UnitPrice  *  Mgmt_Fee_Percent__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Monthly Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>TotalMonthlyCharge__c</fullName>
        <description>OLI total Monthly Charge Amount</description>
        <label>Total Monthly Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Updates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/InvoiceAdjustmentCntrl.cls
public class InvoiceAdjustmentCntrl {
 Public Id oliId {set;get;}
 public Invoice_LineItem__c ili {set;get;}    
 public InvoiceAdjustmentCntrl() {
   oliId = ApexPages.currentPage().getParameters().get('oliid'); 
   ili = new Invoice_LineItem__c();  
    
 }
    
 public pageReference adjustInvoiceDetails()
 {
  PageReference ref = new PageReference('/apex/OpportunityLineItemUSCP?id='+oliId); 
     
     OpportunityLineItem oli1 = [select id,name,Project__c,OpportunityId from OpportunityLineItem where id=:oliId];
 // List<Invoice_LineItem__c> invLineItemLst  = [select id,name,TotalMonthlyCharge__c,InvoiceType__c,Invoice_PeriodStart__c,Invoice_PeriodEnd__c,Invoice_ScheduleDate__c,OpportunityRef__c,ProjectRef__c from Invoice_LineItem__c where OpportunityRef__c =:oli1.OpportunityId  and ProjectRef__c =:oli1.Project__c];
     boolean errFlag = false;
     String errMsg = 'Please select';
     if(ili.Invoice_CreditOrDebit__c == null)
     {    errFlag = true;
          errMsg = errMsg +' Credit or Debit';
     }
      
     if(ili.Invoice_CreditOrDebit_Reason__c == null)
     {
      if(errFlag)
          errMsg = errMsg +' , Adjustment Reason';
         else
           errMsg = errMsg +' Adjustment Reason';
           
         errFlag = true;
        
     }
     if(ili.TotalMonthlyCharge__c == null)
     {
       if(errFlag)
       errMsg = errMsg +' and enter an Amount';
       else
        errMsg = 'Please enter an Amount';
        
         errFlag = true;
        
     }  
       
     
     if(errFlag)
     {
         ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,errMsg));
         ref = null;
     }
     else if(oli1.Project__c != null)
     {
       Invoice_LineItem__c ili1 = new Invoice_LineItem__c();
        ili1.Invoice_LineItemType__c = 'Adjustment';
      if(ili.Invoice_CreditOrDebit__c == 'Credit')
     {
          ili1.TotalMonthlyCharge__c = (-ili.TotalMonthlyCharge__c);
         
     }
     else if(ili.Invoice_CreditOrDebit__c == 'Debit')
     {
         ili1.TotalMonthlyCharge__c = (ili.TotalMonthlyCharge__c);   
     }
         ili1.Invoice_CreditOrDebit_Reason__c =  ili.Invoice_CreditOrDebit_Reason__c;
         ili1.Invoice_PeriodStart__c  = date.today();
         ili1.Invoice_PeriodEnd__c  = date.today();
         ili1.Invoice_CreditOrDebit__c = ili.Invoice_CreditOrDebit__c;
         ili1.Invoice_AdjustmentDetails__c = ili.Invoice_AdjustmentDetails__c;
         ili1.OpportunityRef__c = oli1.OpportunityId;
         ili1.ProjectRef__c = oli1.Project__c;
         
         insert ili1;
     }  
   
   return ref;  
 }

    public PageReference cancel()
    {
        PageReference ref = new PageReference('/apex/OpportunityLineItemUSCP?id='+oliId);
        
        return ref;
    }
}