prod_snapshot_2015-09-24_1030/objects/Invoice_LineItem__c.object
<CustomObject>
    <description>Maintains all Invoice records which can be used for billing .</description>
    <fields>
        <fullName>Invoice_LineItemType__c</fullName>
        <label>ILI Type</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kill</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Invoice_PeriodEnd__c</fullName>
        <label>Period End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_PeriodStart__c</fullName>
        <label>Period Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_ScheduleDate__c</fullName>
        <formula>IF( MONTH(Invoice_PeriodStart__c) &lt;&gt; 12 ,
    DATE( YEAR(Invoice_PeriodStart__c) , MONTH(Invoice_PeriodStart__c)+1 ,1),
    DATE( YEAR(Invoice_PeriodStart__c)+1 , 1 ,1))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ILI Schedule Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsSystemGenerated__c</fullName>
        <formula>OR(
Text(Invoice_LineItemType__c) == &apos;Standard&apos;,
Text(Invoice_LineItemType__c) == &apos;Cancellation&apos;,
Text(Invoice_LineItemType__c) == &apos;Cancel&apos;,
Text(Invoice_LineItemType__c) == &apos;Kill&apos;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is System Generated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mgmt_Fee__c</fullName>
        <formula>IF(OR(ISPICKVAL(Invoice_LineItemType__c,&apos;Manual&apos;),ISPICKVAL(Invoice_LineItemType__c,&apos;Adjustment&apos;)),null,ProjectRef__r.Mgmt_Fee_Percent__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mgmt Fee %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OpportunityRef__c</fullName>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Price__c</fullName>
        <formula>ProjectRef__r.UnitPrice__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectRef__c</fullName>
        <label>Related Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TotalMonthlyCharge__c</fullName>
        <label>Total Monthly Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>isDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Locked</label>
        <type>Checkbox</type>
    </fields>
    <label>ILI</label>
    <nameField>
        <displayFormat>ILI-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Invoice_CancelDate__c</fullName>
        <label>Invoice Cancel Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_ServiceEndDate__c</fullName>
        <label>Product End of Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_ServiceStartDate__c</fullName>
        <label>Product Start of Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Id__c</fullName>
        <formula>PricebookEntry.Product2.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Qty_ContractMonths__c</fullName>
        <label>Number of Contract Months</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalMonthlyCharge__c</fullName>
        <formula>UnitPrice  + (UnitPrice  *  Mgmt_Fee_Percent__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Monthly Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Waiting_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Onboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting On Client Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting On Client Resource</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hard Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Non-Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled-Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>--Internal Use Only--</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused:Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused:No Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>HasMediaSpend__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Media Spend</description>
        <label>Has Media Spend</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Frequency__c</fullName>
        <description>USCP Custom Field: Invoice Frequency</description>
        <label>Invoice Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Two Times</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>HasMediaSpend__c</fullName>
        <formula>Related_Product__r.HasMediaSpend__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Has Media Spend</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_CancelDate__c</fullName>
        <label>Invoice Cancel Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_ServiceEndDate__c</fullName>
        <label>Product End of Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_ServiceStartDate__c</fullName>
        <label>Product Start of Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Id__c</fullName>
        <label>Product Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qty_ContractMonths__c</fullName>
        <label>Qty Contract Months</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Related_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalMonthlyCharge__c</fullName>
        <description>OLI total Monthly Charge Amount</description>
        <label>Total Monthly Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Updates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/USCPILIGenerator.cls
public class USCPILIGenerator extends AbstractInvoiceLineItemsClass{  
	
	//Regen ILIs per the new logic DEV-3111 
	//Donot delete ILIs that are marked as Locked OR Passed Invoice Schedule Date.
    public void regenerateInvoiceLineItems(map < Id, Id > oliIdWithProjectMap) {
    	List < OpportunityLineItem > oliList = new List < OpportunityLineItem > ();
    	oliList = [SELECT Id, PricebookEntry.Product2.Invoice_Frequency__c,
						OpportunityId, Qty_ContractMonths__c,
						Invoice_ServiceStartDate__c, TotalMonthlyCharge__c, 
						Waiting_status__c, Project__c
					FROM OpportunityLineItem
					WHERE Id IN: oliIdWithProjectMap.keyset()];
		
    	system.debug('********oliIdWithProjectMap1111**********' + oliIdWithProjectMap);
    	system.debug('********oliList**********' + oliList);
    	
    	//Filtering newOLIList by removing Cancel and Hard Cancel OLIs
    	List < OpportunityLineItem > newOliList = new List < OpportunityLineItem > ();
    	for(OpportunityLineItem oneOLI : oliList){
    		Boolean exclude = false;
    		//DONOT Support ILI Regen on Two times product
    		if(oneOLI.PricebookEntry.Product2.Invoice_Frequency__c == 'Two Times'){
    			exclude = true;
    			oliIdWithProjectMap.remove(oneOLI.Id);	 
    			System.debug('Ignoring OLI for ILI Regen because its Cancelled and the status is >> ' + oneOLI);
    		} 
    		
    		//DONOT Support ILI Regen on Cancelled OLIs
    		if(oneOLI.Waiting_status__c != null 
    			&& (oneOLI.Waiting_status__c == 'Cancelled' || oneOLI.Waiting_status__c == 'Hard Cancel')){
    			exclude = true;
    			oliIdWithProjectMap.remove(oneOLI.Id);	 
    			System.debug('Ignoring OLI for ILI Regen because its Cancelled and the status is >> ' + oneOLI);
    		} 
    		
    		if(!exclude){
    			newOliList.add(oneOLI);
    		}
    	}
    	
    	if(newOliList.size()==0){
    		System.debug('OLIs didnot meet the criteria for ILI Regen hence moving back');
    		return;
    	}
    	
    	//Retrieve existing  ILIs which are isLocked and IsSystemGenerated for Delete
    	List<Invoice_LineItem__c> deleteUnlockedILIs = [Select Id, Name from Invoice_LineItem__c 
    													Where ProjectRef__c In: oliIdWithProjectMap.Values()
    													and IsSystemGenerated__c=true
    													and isLocked__c=false];
    	
    	//Retrieve existing  ILIs which are isLocked and IsSystemGenerated
    	Map<Id, Project__c> mapExistingILIs = new Map<Id, Project__c>();
    	mapExistingILIs.putAll([Select Id, (Select Id, Name, Invoice_ScheduleDate__c, 
    										 	Invoice_PeriodEnd__c, Invoice_PeriodStart__c, 
    										 	IsSystemGenerated__c, isLocked__c  
    										 from Invoice_Line_Items__r
    										 Where isLocked__c=true and IsSystemGenerated__c=true)
	    							 from Project__c
	    						Where Id In: oliIdWithProjectMap.Values()]);
    	System.debug ('Existing ILIs >> ' + mapExistingILIs); 
    							 
    	//Map of Project Ids with ILI List
		Map<Id, List<Invoice_LineItem__c>> mapILIList = new Map<Id, List<Invoice_LineItem__c>>();
		for (OpportunityLineItem oli: newOliList) {
			Integer qtyContractMonths = Integer.valueOf(oli.Qty_ContractMonths__c);
			Decimal oliMonthlyTotal = oli.TotalMonthlyCharge__c;
			Date startDate = oli.Invoice_ServiceStartDate__c;
			Id opportunityId = oli.opportunityId;
			Id projectId = oliIdWithProjectMap.get(oli.Id);
			
			List<Invoice_LineItem__c> newILIList = new List<Invoice_LineItem__c>(); 
			
			//Calling abstract class create method to get the List of returned Invoice LineItems created for OLI's  
			system.debug('********oli.PricebookEntry.Product2.Invoice_Frequency__c**********' + oli.PricebookEntry.Product2.Invoice_Frequency__c);
			if (oli.PricebookEntry.Product2.Invoice_Frequency__c != 'Two Times') {
				newILIList.addall(createInvoiceLineItems(qtyContractMonths, startDate, oliMonthlyTotal, opportunityId, projectId));
				
				newILIList = regenCreateInvoiceLineItems(mapExistingILIs.get(projectId).Invoice_Line_Items__r, newILIList);
			}			
			mapILIList.put(projectId, newILIList);
		}
    	
    	//Calling Insert method of abstract class to create Invoice LIneItems for the OLI's
    	if (mapILIList != null && mapILIList.size() > 0) {
    		List<Invoice_LineItem__c> invoiceLineItemList = new List<Invoice_LineItem__c>();
    		for(Id projectId : mapILIList.KeySet()){
    			invoiceLineItemList.addall(mapILIList.get(projectId));
    		}
    		system.debug('********invoiceLineItemList**********' + invoiceLineItemList);
    		super.insertInvoiceLineItems(invoiceLineItemList);
    	}
    	
    	//delete UnLocked System Generated ILIs as part of ILI Regeneration 
    	if(deleteUnlockedILIs!=null && deleteUnlockedILIs.size()>0){
    		delete deleteUnlockedILIs;
    	}
    }
   
   //Getting the Opportunity LineItems and to be generated Invoice LiteItems for the associated Oppoortunity LineItems
    public void insertInvoiceLineItems(map<Id, Id> oliIdWithProjectMap)
    {
        List<Invoice_LineItem__c> invoiceLineItemList = new List<Invoice_LineItem__c>();
        List<OpportunityLineItem> oliList = new List<OpportunityLineItem>();
        oliList = [SELECT Id,  PricebookEntry.Product2.Invoice_Frequency__c, OpportunityId, Qty_ContractMonths__c, Invoice_ServiceStartDate__c,TotalMonthlyCharge__c 
                                       FROM OpportunityLineItem 
                                       WHERE Id IN : oliIdWithProjectMap.keyset()];
        
        system.debug('********oliIdWithProjectMap1111**********'+oliIdWithProjectMap);
        system.debug('********oliList**********'+oliList);
        if(oliList.size()>0){                             
        for(OpportunityLineItem oli : oliList){                      
            Integer qtyContractMonths= Integer.valueOf(oli.Qty_ContractMonths__c);
            Decimal oliMonthlyTotal = oli.TotalMonthlyCharge__c; 
            Date startDate = oli.Invoice_ServiceStartDate__c;
            Id opportunityId = oli.opportunityId;
            Id projectId = oliIdWithProjectMap.get(oli.Id);
          
            //Calling abstract class create method to get the List of returned Invoice LineItems created for OLI's  
            system.debug('********oli.PricebookEntry.Product2.Product_Type_Dummy__c**********'+oli.PricebookEntry.Product2.Invoice_Frequency__c);
            if(oli.PricebookEntry.Product2.Invoice_Frequency__c!= 'Two Times'){
                invoiceLineItemList.addall(createInvoiceLineItems(qtyContractMonths,  startDate, oliMonthlyTotal, opportunityId, projectId));
            }
            else if(oli.PricebookEntry.Product2.Invoice_Frequency__c== 'Two Times'){
                invoiceLineItemList.addall(createInvoiceLineItemsForONEProduct(qtyContractMonths,  startDate, oliMonthlyTotal, opportunityId, projectId));
            }
        
        }        
        
       } 
       
       //Calling Insert method of abstract class to create Invoice LIneItems for the OLI's
        if(invoiceLineItemList!= null && invoiceLineItemList.size()>0){
            
            system.debug('********invoiceLineItemList**********'+invoiceLineItemList);            
            super.insertInvoiceLineItems(invoiceLineItemList);
        }
    }
    
    
    // Getting the ILI's for all the project Id's and performing soft delete if cancel on OLI occurs.
    // DEV-2588 FIP - Bulkify Cancel and Hard Cancellation Rules Methods
    public void cancelInvoiceLineItems(set < Id > projIds) {
    	//Retrive all OLIs with Project Id
    	Map < Id, OpportunityLineItem > mapOLIs = new Map < Id, OpportunityLineItem > ();
    	mapOLIs.putAll([SELECT Id, Invoice_ServiceStartDate__c, Invoice_ServiceEndDate__c, project__c,
    	Invoice_CancelDate__c, PricebookEntry.Product2.Invoice_Frequency__c
    	FROM OpportunityLineItem WHERE project__c IN: projIds]);


    	//Retrieve All ILIs for the corresponding ProjectIds
    	List < Invoice_LineItem__c > getinvLineItemList = new List < Invoice_LineItem__c > ();
    	getinvLineItemList = [SELECT Id, Invoice_PeriodStart__c, OpportunityRef__c, Invoice_ScheduleDate__c,
							    	ProjectRef__c, TotalMonthlyCharge__c, isLocked__c,
							    	isDeleted__c, Invoice_PeriodEnd__c, Mgmt_Fee__c, Product_Price__c,
							    	ProjectRef__r.Product_Id__c, ProjectRef__r.Invoice_CancelDate__c,
                                    ProjectRef__r.Related_Product__r.HasMediaSpend__c
						    	FROM Invoice_LineItem__c
						    	WHERE ProjectRef__c In: projIds
							    	AND isDeleted__c = false
							    	AND isLocked__c = false
							    	And IsSystemGenerated__c = true
						    	ORDER BY ProjectRef__c, Invoice_PeriodStart__c ASC];

    	//Store map of OLIs with corresponding ILIs                                         					
    	Map < Id, List < Invoice_LineItem__c >> mapOLIsILIs = new Map < Id, List < Invoice_LineItem__c >> ();
        if(getinvLineItemList != null && getinvLineItemList.size() > 0){
            for (Invoice_LineItem__c oneILI: getinvLineItemList) {
                List < Invoice_LineItem__c > listOLIILIs = mapOLIsILIs.get(oneILI.ProjectRef__r.Product_Id__c);
                if (listOLIILIs == null) {
                    listOLIILIs = new List < Invoice_LineItem__c > ();
                    mapOLIsILIs.put(oneILI.ProjectRef__r.Product_Id__c, listOLIILIs);
                }
    
                //SOQL Criteria moved here (Invoice_ScheduleDate__c >: cancelDate OR Invoice_ScheduleDate__c = null)
                if (oneILI.Invoice_ScheduleDate__c > oneILI.ProjectRef__r.Invoice_CancelDate__c || oneILI.Invoice_ScheduleDate__c == null) {
                    listOLIILIs.add(oneILI);
                }
            }
         }
    
    	//Cancellation Logic starts here
    	List < Invoice_LineItem__c > megeredILIs = new List < Invoice_LineItem__c > ();
    	List < Invoice_LineItem__c > deleteILIs = new List < Invoice_LineItem__c > ();
    	for (OpportunityLineItem oneOppLineItem: mapOLIs.values()) {
    		date cancelDate = oneOppLineItem.Invoice_CancelDate__c;
    		date serviceStartDate = oneOppLineItem.Invoice_ServiceStartDate__c;
    		String invoiceFrequency = oneOppLineItem.PricebookEntry.Product2.Invoice_Frequency__c;
    		date serviceEndDate;
    		date minimumMonths;

    		if (cancelDate > serviceStartDate.addmonths(3)) {
    			//minimum 2 month rule
    			minimumMonths = cancelDate.addmonths(2);
    		} else {
    			//minimum 4 month rule
    			minimumMonths = serviceStartDate.addmonths(4);
    		}
             if(mapOLIsILIs.get(oneOppLineItem.Id) != null){
                if (invoiceFrequency != null && invoiceFrequency != 'Two Times') {
                   
                    System.debug('getinvLineItemList >> ' + mapOLIsILIs.get(oneOppLineItem.Id));
                    Invoice_LineItem__c newILI;
                    
                    for (Invoice_LineItem__c oneILI: mapOLIsILIs.get(oneOppLineItem.Id)) {
                        if (oneILI.Invoice_PeriodEnd__c <= minimumMonths) {
                            newILI = (newILI == null ? new Invoice_LineItem__c() : newILI);
                            if (newILI.Invoice_PeriodStart__c == null) {
                                newILI.Invoice_PeriodStart__c = oneILI.Invoice_PeriodStart__c;
                                newILI.OpportunityRef__c = oneILI.OpportunityRef__c;
                                newILI.ProjectRef__c = oneILI.ProjectRef__c;
                                newILI.TotalMonthlyCharge__c = oneILI.TotalMonthlyCharge__c;
                                newILI.Invoice_LineItemType__c = 'Cancel';
                                newILI.Invoice_PeriodEnd__c = oneILI.Invoice_PeriodStart__c.addMonths(1).addDays(-1);
                            } else {
                                newILI.TotalMonthlyCharge__c = newILI.TotalMonthlyCharge__c + oneILI.TotalMonthlyCharge__c;
                            }
                            serviceEndDate = oneILI.Invoice_PeriodEnd__c;
                        }
                    }
                    System.debug('new ILI >> ' + newILI);
                    if (newILI != null) {
                        megeredILIs.add(newILI);
                        oneOppLineItem.Invoice_ServiceEndDate__c = serviceEndDate;
                    }
                } else {
                    oneOppLineItem.Invoice_ServiceEndDate__c = cancelDate;
                }
                deleteILIs.addAll(mapOLIsILIs.get(oneOppLineItem.Id));
              }
            }

    	//insert new ILI 
    	if (megeredILIs.size() > 0) {
    		super.insertInvoiceLineItems(megeredILIs);
    	}

    	//delete Cancelled ILIs
    	if (deleteILIs.size() > 0) {
    		super.deleteInvoiceLineItems(deleteILIs);
    	}

    	//update OLI
    	if (mapOLIs.values().size() > 0) {
    		update mapOLIs.values();
    	}
    }
    
    // Update the Start and End Dates of ILI whose Product2.Invoice_Frequency__c == 'Two Times'
    public void updateInvoiceLineItems(map<Id, Id> oliIdWithProjectMap)
    {
        List<Invoice_LineItem__c> iliList = new List<Invoice_LineItem__c>();
        
        
        set<Id> projIds = new set<Id>();
        for(OpportunityLineItem  oli : [SELECT Id, PricebookEntry.Product2.Invoice_Frequency__c, Invoice_ServiceEndDate__c,Invoice_ServiceStartDate__c  FROM OpportunityLineItem 
                                       WHERE project__c IN : oliIdWithProjectMap.values()]){
            
            if(oli.PricebookEntry.Product2.Invoice_Frequency__c == 'Two Times' && oli.Invoice_ServiceStartDate__c != null && oli.Invoice_ServiceEndDate__c!= null){
                projIds.add(oliIdWithProjectMap.get(oli.Id));
            }                               
        }
        
        
        for(Invoice_LineItem__c ili : [SELECT Id, Invoice_PeriodStart__c, OpportunityRef__c, Invoice_ScheduleDate__c,
                                                        ProjectRef__c, TotalMonthlyCharge__c, isLocked__c,
                                                        isDeleted__c, Invoice_PeriodEnd__c
                                                 FROM Invoice_LineItem__c
                                                 WHERE ProjectRef__c In : projIds
                                                     AND isDeleted__c = false
                                                     AND isLocked__c = false
                                                     And IsSystemGenerated__c = true
                                                     And Invoice_PeriodEnd__c = null
                                                     AND Invoice_PeriodStart__c = null
                                                 ORDER BY ProjectRef__c, Invoice_PeriodStart__c ASC]){
        
            ili.Invoice_PeriodStart__c = date.today();
            ili.Invoice_PeriodEnd__c = date.today().addmonths(1).adddays(-1);
            iliList.add(ili);
        }
        super.updateInvoiceLineItems(iliList);
    }
    
    public void hardCancelInvoiceLineItems(set<Id> projIds)
    {   
    	//Retrive all OLIs with Project Id
    	Map < Id, OpportunityLineItem > mapOLIs = new Map < Id, OpportunityLineItem > ();
    	mapOLIs.putAll([SELECT Id, Invoice_ServiceStartDate__c, Invoice_ServiceEndDate__c, project__c,
    	Invoice_CancelDate__c, PricebookEntry.Product2.Invoice_Frequency__c
    	FROM OpportunityLineItem WHERE project__c IN: projIds]);


    	//Retrieve All ILIs for the corresponding ProjectIds
    	List < Invoice_LineItem__c > getinvLineItemList = new List < Invoice_LineItem__c > ();
    	getinvLineItemList = [SELECT Id, Invoice_PeriodStart__c, OpportunityRef__c, Invoice_ScheduleDate__c,
							    	ProjectRef__c, TotalMonthlyCharge__c, isLocked__c,
							    	isDeleted__c, Invoice_PeriodEnd__c, Mgmt_Fee__c, Product_Price__c,
							    	ProjectRef__r.Product_Id__c, ProjectRef__r.Invoice_CancelDate__c,
                                    ProjectRef__r.Related_Product__r.HasMediaSpend__c
						    	FROM Invoice_LineItem__c
						    	WHERE ProjectRef__c In: projIds
							    	AND isDeleted__c = false
							    	AND isLocked__c = false
							    	And IsSystemGenerated__c = true
						    	ORDER BY ProjectRef__c, Invoice_PeriodStart__c ASC];

    	//Store map of OLIs with corresponding ILIs                                         					
    	Map < Id, List < Invoice_LineItem__c >> mapOLIsILIs = new Map < Id, List < Invoice_LineItem__c >> ();
        if(getinvLineItemList != null && getinvLineItemList.size() > 0){
            for (Invoice_LineItem__c oneILI: getinvLineItemList) {
                List < Invoice_LineItem__c > listOLIILIs = mapOLIsILIs.get(oneILI.ProjectRef__r.Product_Id__c);
                if (listOLIILIs == null) {
                    listOLIILIs = new List < Invoice_LineItem__c > ();
                    mapOLIsILIs.put(oneILI.ProjectRef__r.Product_Id__c, listOLIILIs);
                }
    
                //SOQL Criteria moved here (Invoice_ScheduleDate__c >: cancelDate OR Invoice_ScheduleDate__c = null)
                if (oneILI.Invoice_ScheduleDate__c > oneILI.ProjectRef__r.Invoice_CancelDate__c || oneILI.Invoice_ScheduleDate__c == null) {
                    listOLIILIs.add(oneILI);
                }
            }
        }
    	//Cancellation Logic starts here
    	List < Invoice_LineItem__c > megeredILIs = new List < Invoice_LineItem__c > ();
    	List < Invoice_LineItem__c > deleteILIs = new List < Invoice_LineItem__c > ();
    	for (OpportunityLineItem oneOppLineItem: mapOLIs.values()) {
    		date cancelDate = oneOppLineItem.Invoice_CancelDate__c;
    		date serviceStartDate = oneOppLineItem.Invoice_ServiceStartDate__c;
    		String invoiceFrequency = oneOppLineItem.PricebookEntry.Product2.Invoice_Frequency__c;
    		date serviceEndDate;
    		date minimumMonths;

    		if (cancelDate > serviceStartDate.addmonths(3)) {
    			//minimum 2 month rule
    			minimumMonths = cancelDate.addmonths(2);
    		} else {
    			//minimum 4 month rule
    			minimumMonths = serviceStartDate.addmonths(4);
    		}
            if(mapOLIsILIs.get(oneOppLineItem.Id) != null){
                if (invoiceFrequency != null && invoiceFrequency != 'Two Times') {
                    System.debug('getinvLineItemList >> ' + mapOLIsILIs.get(oneOppLineItem.Id));
                    Invoice_LineItem__c newILI;
                    for (Invoice_LineItem__c oneILI: mapOLIsILIs.get(oneOppLineItem.Id)) {
                        if (oneILI.Invoice_PeriodEnd__c <= minimumMonths) {
                            newILI = (newILI == null ? new Invoice_LineItem__c() : newILI);
                            if (newILI.Invoice_PeriodStart__c == null) {
                                newILI.Invoice_PeriodStart__c = oneILI.Invoice_PeriodStart__c;
                                newILI.OpportunityRef__c = oneILI.OpportunityRef__c;
                                newILI.ProjectRef__c = oneILI.ProjectRef__c;
                                if(oneILI.Invoice_PeriodStart__c !=null && cancelDate < oneILI.Invoice_PeriodStart__c && oneILI.ProjectRef__r.Related_Product__r.HasMediaSpend__c==true && oneILI.Product_Price__c != null && 
                                   oneILI.Mgmt_Fee__c != null){
                                     newILI.TotalMonthlyCharge__c=  oneILI.Product_Price__c* oneILI.Mgmt_Fee__c/100; 
                                   }else{
                                     newILI.TotalMonthlyCharge__c = oneILI.TotalMonthlyCharge__c;
                                   }
                                newILI.Invoice_LineItemType__c= 'Kill';
                                newILI.Invoice_PeriodEnd__c = oneILI.Invoice_PeriodStart__c.addMonths(1).addDays(-1);
                            }else if (oneILI.ProjectRef__r.Related_Product__r.HasMediaSpend__c==true && oneILI.Product_Price__c != null && 
                                     oneILI.Mgmt_Fee__c != null){
                                newILI.TotalMonthlyCharge__c= newILI.TotalMonthlyCharge__c+ (oneILI.Product_Price__c* oneILI.Mgmt_Fee__c/100);                  
                            }
                            else{
                                newILI.TotalMonthlyCharge__c= newILI.TotalMonthlyCharge__c+ oneILI.TotalMonthlyCharge__c;
                            }
                        }
                    }
                    System.debug('new ILI >> ' + newILI);
                    if (newILI != null) {
                        megeredILIs.add(newILI);
                        oneOppLineItem.Invoice_ServiceEndDate__c = cancelDate;
                    }
                } else {
                    oneOppLineItem.Invoice_ServiceEndDate__c = cancelDate;
                }
                deleteILIs.addAll(mapOLIsILIs.get(oneOppLineItem.Id));
            }
    	}

    	//insert new ILI 
    	if (megeredILIs.size() > 0) {
    		super.insertInvoiceLineItems(megeredILIs);
    	}

    	//delete Cancelled ILIs
    	if (deleteILIs.size() > 0) {
    		super.deleteInvoiceLineItems(deleteILIs);
    	}

    	//update OLI
    	if (mapOLIs.values().size() > 0) {
    		update mapOLIs.values();
    	}  	
    	    
    }
}