prod_snapshot_2015-09-24_1030/objects/KPICalender__c.object
<CustomObject>
    <fields>
        <fullName>CurrentPeriod2__c</fullName>
        <description>This is the Current Period updated by an Apex scheduled job. the Field CurrentPeriod, will point to this one</description>
        <label>CurrentPeriod2</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Period_Offset__c</fullName>
        <description>This will be the offset of the current period versus this instance of the KPICalender Period. Negative means current is later than KPI, Positive means Current is Earlier than KPI.

This wil replace the logid in code period. Code period will then just point to this field.</description>
        <label>Period Offset</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <picklist>
            <picklistValues>
                <fullName>P01</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P02</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P03</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P04</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P05</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P06</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P07</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P08</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P09</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>KPI Calender</label>
    <nameField>
        <label>Date</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KPIs Calender</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/KpiCalenderManager.cls
public with sharing class KpiCalenderManager {
	
	public void updateNewFiscalPeriod(){
		Date currentDate = Date.today();
		Integer currentYear = currentDate.year();
		List<Period> periodToday = [select Number
									from Period
									where StartDate <= :currentDate
									and EndDate >= :currentDate
									and Type = 'Month' limit 1];
		if(periodToday == null || periodToday.size() != 1){
			system.debug('Period query didn\'t return expected results ... canceling update operation');
			return;
		}
		Integer intCurrentPeriod = periodToday[0].Number;
		String strCurrentPeriod = intCurrentPeriod < 10 ? 'P0' + String.valueOf(intCurrentPeriod) : 'P' + String.valueOf(intCurrentPeriod);
								 
		// See what the previous value was for any KPICalender record
		List<KPICalender__c> todayCal = [Select CurrentPeriod2__c From KPICalender__c limit 1];
		if(todayCal == null || todayCal.size() != 1){
			system.debug('KPICal for today didn\'t return expected results ... canceling update operation');
			return;
		}
		
		String strPrevUpdatedPeriod = todayCal[0].CurrentPeriod2__c;
		if(strCurrentPeriod == strPrevUpdatedPeriod){
			system.debug('Period is still current. No update necessary');
		}
		else {
			system.debug('CurrentPeriod is changing from ' + strPrevUpdatedPeriod + ' to ' + strCurrentPeriod);
			List<KPICalender__c> KpiCalsToUpdate = new List<KPICalender__c>();
			for(List<KPICalender__c> KpiCalBatch : [Select 	Id,
															Period__c,
															currentPeriod2__c,
															Period_Offset__c,
															Fiscal_Year__c
															From KPICalender__c]){
				for(KPICalender__c KpiCal : KpiCalBatch){
					// Set current Period
					KpiCal.currentPeriod2__c = strCurrentPeriod;
					
					// Now calculate and set the Period Offset
					Integer KpiPeriod = Integer.valueOf(KpiCal.Period__c.right(2));
					
					// Start with some Year+Period as a "zero point" I'll use P01 of 2000, because
					// it's far enough in the past to not conflict with any actual data and it's a nice round number.
					Integer baseYear = 2000;
					Integer totalCurrentPeriods = (currentYear - baseYear)*12 + intCurrentPeriod;
					
					Integer totalKpiPeriods = ((Integer)KpiCal.Fiscal_Year__c - baseYear)*12 + KpiPeriod;
					
					// Period Offset =  Kpi - Current. This makes the sign negative for Kpi periods
					// in the past and positive for Kpi periods in the future
					Integer PeriodOffset = totalKpiPeriods - totalCurrentPeriods;
					
					KpiCal.Period_Offset__c = PeriodOffset;
					KpiCalsToUpdate.Add(KpiCal);
					
					
					
				}
			}
			update KpiCalsToUpdate;
		}
	} // updateNewFiscalPeriod()
	
	public void resetCurrentPeriodForTesting(String periodToSet){
		system.debug('Changing CurrentPeriod to ' + periodToSet);
		List<KPICalender__c> KpiCalsToUpdate = new List<KPICalender__c>();
		for(List<KPICalender__c> KpiCalBatch : [Select 	Id,
														currentPeriod2__c
														From KPICalender__c]){
			for(KPICalender__c KpiCal : KpiCalBatch){
				// Set current Period
				KpiCal.currentPeriod2__c = periodToSet;
				
				KpiCalsToUpdate.Add(KpiCal);
				
				
				
			} // inner for loop
		} // outer for loop
		update KpiCalsToUpdate;
	} // resetCurrentPeriodForTesting() 

}