prod_snapshot_2015-09-24_1030/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Do_Not_Redistribute__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Do Not Redistribute - Prevents This Lead From Being Transferred To The Open Acq Queue Owner.</inlineHelpText>
        <label>DNR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Former_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Former Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leads2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Touch_Age__c</fullName>
        <description>TODAY() - DATEVALUE(Last_Touch_Date__c)</description>
        <formula>TODAY() - Last_Touch_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Touch Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stale_Transfer_Date__c</fullName>
        <label>Stale Transfer Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status_Explanation__c</fullName>
        <inlineHelpText>Enter The Reason For The Status - Required On Some Status Selections</inlineHelpText>
        <label>Status Explanation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>SML_Lead</fullName>
        <active>true</active>
        <businessProcess>SML Lead Process</businessProcess>
        <label>SML Lead</label>
    </recordTypes>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/OwnershipTransferSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Holds min and max values for ownership transfer</description>
    <fields>
        <fullName>MaxDaysNoTouch__c</fullName>
        <description>Max days to transfer - currently this isn&apos;t set leading to 10k&apos;s of unnecessary attempts to transfer old leads</description>
        <label>MaxDaysNoTouch</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MinDaysNoTouch__c</fullName>
        <description>The low end of the query ex. 11 for Lead, 31 for Opportunity</description>
        <label>MinDaysNoTouch</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Ownership Transfer settings</label>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/batchonLead_transferOwner.cls
// Note - when using the start method with QueryLocator, you must define the interface with 
// sObject instead of a specific type
global class batchonLead_transferOwner implements Database.Batchable<sObject>{

	global Database.QueryLocator start(database.batchablecontext BC){
		  
		//Defaults for ages as of 6/18/2014 per conversation with Adam Claypool and Phil Pratt
		Integer minAge = Constants.LEAD_TRANSFER_MIN_AGE;
		Integer maxAge = 365;
		  
		// Get the Custom settings for low and high values 
		OwnershipTransferSettings__c leadMinMaxAge = OwnershipTransferSettings__c.getValues('Lead');
		if (leadMinMaxAge != null)
		{
		  	//Never allow the min age to drop below the defined value! 
		    //Greater than is fine in order to reduce the dataset for older leads
		  	minAge = leadMinMaxAge.MinDaysNoTouch__c < Constants.LEAD_TRANSFER_MIN_AGE
		  				? Constants.LEAD_TRANSFER_MIN_AGE
		  				: (Integer)leadMinMaxAge.MinDaysNoTouch__c;
		  	
		  	maxAge = (Integer)leadMinMaxAge.MaxDaysNoTouch__c;
		  	
		}
		  
		system.debug('min / mage age = ' + minAge + '/' + maxAge);
		
		// Exclude LeadGen Profiles
		ID leadGenSpecialist = ProfileCache.getProfile('Lead Generation Specialists').Id;
		ID leadGenSupervisor = ProfileCache.getProfile('Lead Gen Supervisor').Id;
		
		// Get the QueryLocator for the Query
		// <PWP 6/19/2014> Changed the Owener criteria to force it to be User - otherwise the assignment to Former Owner fails
		Database.QueryLocator ql = Database.getQueryLocator(
									[SELECT id, OwnerId, Status_Explanation__c, Former_Owner__c
									FROM Lead
									WHERE RecordTypeId = :RecordTypeCache.getRecordType('Lead', 'SML_Lead').ID
									AND Owner.Type = 'User'
									AND Owner.ProfileId NOT IN (:leadGenSpecialist, :leadGenSupervisor)
									AND IsConverted = False
									AND Do_Not_Redistribute__c = False
									AND Last_Touch_Age__c >= :minAge
									AND Last_Touch_Age__c <= :maxAge]);
	
		if(ql == null)
		{
			system.debug('QueryLocator was null');
		}
		else
		{
			system.debug('Query used:' + ql.getQuery());
		}
		return ql;
	}

	global void execute(Database.BatchableContext BC, List<Lead> scope){
		// <refactor> place this logic in a service class 
		// <refactor> no error handling 
		try
		{
			List<Lead> leadsToUpdate = new List<Lead>();
				for(Lead curLead : scope){
					
					if(curLead.Status_Explanation__c == Null || curLead.Status_Explanation__c.Length() == 0){
						curLead.Status_Explanation__c = 'Stale Transfer';
					}
					curLead.Former_Owner__c = curLead.OwnerId;
					curLead.OwnerId = Constants.OPEN_ACQ_LEADS_QUEUE.Id;
					curLead.Stale_Transfer_Date__c = Date.Today();
					leadsToUpdate.add(curLead);
				} 
				update leadsToUpdate;
		}
		catch(DmlException dmlEx)
		{
			System.debug('DML Exception thrown: ' + dmlEx.getMessage());
		}
		catch(Exception ex)
		{
			System.debug('Exception thrown: ' + ex.getMessage());
		}
	}	
	
	
	global void finish(Database.BatchableContext info){}		

} //class