prod_snapshot_2015-09-24_1030/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Do_Not_Redistribute__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Do Not Redistribute - Prevents This Lead From Being Transferred To The Open Acq Queue Owner.</inlineHelpText>
        <label>DNR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Touch_Age__c</fullName>
        <description>TODAY() - DATEVALUE(Last_Touch_Date__c)</description>
        <formula>TODAY() - Last_Touch_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Touch Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Digital_Fulfillment</fullName>
        <active>true</active>
        <businessProcess>Market Login</businessProcess>
        <label>Digital Fulfillment</label>
    </recordTypes>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Cancel_Reason__c</fullName>
        <label>Cancel Reason</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Do_Not_Redistribute__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Do Not Redistribute - Prevents This Opp From Being Transferred To The Open Acq Queue Owner.</inlineHelpText>
        <label>DNR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Touch_Age__c</fullName>
        <description>TODAY() - DATEVALUE(Last_Touch_Date__c)</description>
        <formula>TODAY() - Last_Touch_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Touch Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Owner__c</fullName>
        <label>Previous Owner</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stale_Transfer__c</fullName>
        <description>Used To Mark When The Last Time An Opp Has Been Transferred To The Stale Activity Queue (Stale Opportunities).</description>
        <label>Stale Transfer</label>
        <type>DateTime</type>
    </fields>
    <recordTypes>
        <fullName>Digital_Fulfillment</fullName>
        <active>true</active>
        <businessProcess>SML Opportunity Process</businessProcess>
        <label>Digital Fulfillment</label>
    </recordTypes>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/OwnershipTransferSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Holds min and max values for ownership transfer</description>
    <fields>
        <fullName>MaxDaysNoTouch__c</fullName>
        <description>Max days to transfer - currently this isn&apos;t set leading to 10k&apos;s of unnecessary attempts to transfer old leads</description>
        <label>MaxDaysNoTouch</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MinDaysNoTouch__c</fullName>
        <description>The low end of the query ex. 11 for Lead, 31 for Opportunity</description>
        <label>MinDaysNoTouch</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Ownership Transfer settings</label>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/batchonOpportunity_transferOwner.cls
// Note - when using the start method with QueryLocator, you must define the interface with 
// sObject instead of a specific type
global class batchonOpportunity_transferOwner implements Database.Batchable<sObject>{

	global Database.QueryLocator start(database.batchablecontext BC){
		//Defaults for ages as of 6/18/2014 per conversation with Adam Claypool and Phil Pratt
		Integer minAge = Constants.OPPORTUNITY_TRANSFER_MIN_AGE;
		Integer maxAge = 365;
		  
		// Get the Custom settings for low and high values 
		OwnershipTransferSettings__c opptyMinMaxAge = OwnershipTransferSettings__c.getValues('Opportunity');
		if (opptyMinMaxAge != null)
		{
		  	//Never allow the min age to drop below the defined value! 
		    //Greater than is fine in order to reduce the dataset for older leads
		  	minAge = opptyMinMaxAge.MinDaysNoTouch__c < Constants.OPPORTUNITY_TRANSFER_MIN_AGE
		  				? Constants.OPPORTUNITY_TRANSFER_MIN_AGE
		  				: (Integer)opptyMinMaxAge.MinDaysNoTouch__c;
		  	
		  	maxAge = (Integer)opptyMinMaxAge.MaxDaysNoTouch__c;
		  	
		}
		  
		system.debug('min / mage age = ' + minAge + '/' + maxAge);

		// Exclude LeadGen Profiles
		ID leadGenSpecialist = ProfileCache.getProfile('Lead Generation Specialists').Id;
		ID leadGenSupervisor = ProfileCache.getProfile('Lead Gen Supervisor').Id;
		
		// Get the QueryLocator for the Query
		Database.QueryLocator ql = Database.getQueryLocator(
								[SELECT Id, OwnerId, Owner.Name, Cancel_Reason__c, Previous_Owner__c
								 FROM Opportunity
								 WHERE RecordTypeId != :RecordTypeCache.getRecordType('Opportunity', 'Digital_Fulfillment').Id
								 AND OwnerId != :Constants.STALE_OPPORTUNITY.Id
								 AND Owner.ProfileId NOT IN (:leadGenSpecialist, :leadGenSupervisor)
								 AND IsClosed = False
								 AND Do_Not_Redistribute__c = False
								 AND Last_Touch_Age__c >= :minAge
								 AND Last_Touch_Age__c <= :maxAge]);
		if(ql == null)
		{
			system.debug('QueryLocator was null');
		}
		else
		{
			system.debug('Query used:' + ql.getQuery());
		}
		return ql;
	}

	global void execute(Database.BatchableContext BC, List<Opportunity> scope){
		// <refactor> place this logic in a service class 
		// <refactor> no error handling 
		List<Opportunity> oppsToUpdate = new List<Opportunity>();
		for(Opportunity oppty : scope){
			if((oppty.Cancel_Reason__c == Null || oppty.Cancel_Reason__c.Length() == 0)){
				oppty.Cancel_Reason__c = 'Stale Transfer';
			}
			
			oppty.Stale_Transfer__c = Datetime.Now();
			oppty.Previous_Owner__c = oppty.Owner.Name;
			oppty.OwnerId = Constants.STALE_OPPORTUNITY.Id;
			oppsToUpdate.add(oppty);
		} 
		update oppsToUpdate;
	}	
	
	global void finish(Database.BatchableContext info){}
}