prod_snapshot_2015-09-24_1030/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Industry_AffiliatedMarkets__c</fullName>
        <inlineHelpText>Help Text</inlineHelpText>
        <label>Industry General</label>
        <picklist>
            <picklistValues>
                <fullName>Automotive Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employment Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospitality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Real Estate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Repair Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales/Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Security Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Industry_Specific__c</fullName>
        <label>Industry Specific</label>
        <picklist>
            <controllingField>Industry_AffiliatedMarkets__c</controllingField>
            <picklistValues>
                <fullName>Aerospace/Defense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apartments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assisted Living</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankruptcy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chemical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cleaning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clothing/Apparel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College/Trade Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collegiate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consignment/Pawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cosmetic Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Criminal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day Care/Pre-School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dental Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elementary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy/Power</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fitness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flooring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funeral Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Furniture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heavy Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High School</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>SML_Lead</fullName>
        <active>true</active>
        <businessProcess>SML Lead Process</businessProcess>
        <label>SML Lead</label>
    </recordTypes>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/beforeOnLead_test.cls
@isTest(SeeallData=true)
public  class beforeOnLead_test {
 static testMethod void testLead(){
     list<user> ulist  =[select id,name,email from user where isactive=true and UserType='Standard' and userrole.name LIKE '%Manager%' limit 1];
     list<lead> insertLeadList = new list<lead>();
     list<lead> insertLeaddataList = new list<lead>();
     for(integer i =0;i<100;i++){
         Lead l = new Lead();
         l.LastName                      = 'Ameda Test'+i;
         l.Company                       = 'test Company' +i;
         l.Status                        = 'Uncontracted-New';
         l.Industry_AffiliatedMarkets__c = 'Education';
         l.Industry_Specific__c          = 'High School';
         l.OwnerId                       = ulist[0].id;
         l.RecordTypeId                  = RecordTypeCache.getRecordType('Lead', 'SML_Lead').Id;
         insertLeadList .add(l);
      }
      insert insertLeadList ;
     
     for(integer i =0;i<50;i++){
         Lead l = new Lead();
         l.LastName                      = 'Ameda Test 2'+i;
         l.Company                       = 'test Company 2'+i;
         l.Status                        = 'Uncontracted-New';
         l.Industry_AffiliatedMarkets__c = 'Education';
         l.Industry_Specific__c          = 'High School';
         l.OwnerId                       = ulist[0].id;
         l.RecordTypeId                  = RecordTypeCache.getRecordType('Lead', 'SML_Lead').Id;
         insertLeaddataList .add(l);
      }
      Test.starttest();
      insert insertLeaddataList ;
      list<lead> leadtestValidate = [select id   from lead where (id in :insertLeaddataList or id In: insertLeadList) ];
      system.assertEquals(leadtestValidate.size(),150);
      test.stopTest();
     
 }
 static testMethod void testBulkLead(){
      string s='%Manager%';
     list<user> ulist  =[select id,name,email from user where isactive=true and UserType='Standard' and userrole.name LIKE '%Manager%' limit 3];
     system.assertEquals(ulist.size(),3);
     list<lead> insertLeadList = new list<lead>();
     for(integer i =0;i<200;i++){
         Lead l = new Lead();
         l.LastName                      = 'Ameda Test'+i;
         l.Company                       = 'test Company' +i;
         l.Status                        = 'Uncontracted-New';
         l.Industry_AffiliatedMarkets__c = 'Education';
         l.Industry_Specific__c          = 'High School';
         l.OwnerId                       = ulist[0].id;
         l.RecordTypeId                  = RecordTypeCache.getRecordType('Lead', 'SML_Lead').Id;
         insertLeadList .add(l);
      }
      for(integer i =0;i<10;i++){
         Lead l = new Lead();
         l.LastName = 'Ameda'+i;
         l.Company = 'testCompany' +i;
         l.Status = 'Uncontracted-New';
         l.Industry_AffiliatedMarkets__c = 'Education';
         l.Industry_Specific__c = 'High School';
         l.OwnerId = ulist[1].id;
         l.RecordTypeId = RecordTypeCache.getRecordType('Lead', 'SML_Lead').Id;
         insertLeadList .add(l);
      }
         insert insertLeadList ;
         list<lead> leadtestValidate1 = [select id  from lead where id in :insertLeadList ];
         //system.assertEquals(leadtestValidate1.size(),210);
          list<lead> updateLeadList = new list<lead>();
          for(integer i=0;i<100;i++){
               Lead l =insertLeadList[i];
               l.ownerid =ulist[1].id;
               updateLeadList.add(l);
          }
          for(integer i=101;i<150;i++){
               Lead l =insertLeadList[i];
               l.ownerid =ulist[2].id;
               updateLeadList.add(l);
          }
         test.starttest();
         update updateLeadList ;
         list<lead> leadtestValidate = [select id  from lead where id in :updateLeadList];
         system.assertEquals(leadtestValidate.size(),149);
         test.stoptest();
   }//End of method testBulkLead
}