prod_snapshot_2015-09-24_1030/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Do_Not_Redistribute__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Do Not Redistribute - Prevents This Lead From Being Transferred To The Open Acq Queue Owner.</inlineHelpText>
        <label>DNR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Former_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Former Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leads2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Touch_Age__c</fullName>
        <description>TODAY() - DATEVALUE(Last_Touch_Date__c)</description>
        <formula>TODAY() - Last_Touch_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Touch Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status_Explanation__c</fullName>
        <inlineHelpText>Enter The Reason For The Status - Required On Some Status Selections</inlineHelpText>
        <label>Status Explanation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>SML_Lead</fullName>
        <active>true</active>
        <businessProcess>SML Lead Process</businessProcess>
        <label>SML Lead</label>
    </recordTypes>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/batchFixLeadGenOwnershipXfer.cls
// Note - when using the start method with QueryLocator, you must define the interface with 
// sObject instead of a specific type
global with sharing class batchFixLeadGenOwnershipXfer implements Database.Batchable<sObject>{

	global Database.QueryLocator start(database.batchablecontext BC){
		  
		//Since Last touch was reset and I was doing these over the course of 2 days, it will only be 0 or 1 
		Integer maxAge = 1;
		
		// Include only LeadGen Profiles for the fix
		ID leadGenSpecialist = ProfileCache.getProfile('Lead Generation Specialists').Id;
		ID leadGenSupervisor = ProfileCache.getProfile('Lead Gen Supervisor').Id;
		
		// Get the QueryLocator for the Query
		// <PWP 6/19/2014> Changed the Owener criteria to force it to be User - otherwise the assignment to Former Owner fails
		Database.QueryLocator ql = Database.getQueryLocator(
									[SELECT id, OwnerId, Status_Explanation__c, Former_Owner__c
									FROM Lead
									WHERE RecordTypeId = :RecordTypeCache.getRecordType('Lead', 'SML_Lead').ID
									AND OwnerId = :Constants.OPEN_ACQ_LEADS_QUEUE.Id
									AND Former_Owner__r.ProfileId IN (:leadGenSpecialist, :leadGenSupervisor)
									AND IsConverted = False
									AND Do_Not_Redistribute__c = False
									AND Last_Touch_Age__c <= :maxAge]);
	
		if(ql == null)
		{
			system.debug('QueryLocator was null');
		}
		else
		{
			system.debug('Query used:' + ql.getQuery());
		}
		return ql;
	}

	global void execute(Database.BatchableContext BC, List<Lead> scope){
		// <refactor> place this logic in a service class 
		// <refactor> no error handling 
		try
		{
			List<Lead> leadsToUpdate = new List<Lead>();
				for(Lead curLead : scope){
					
					if(curLead.Status_Explanation__c == 'Stale Transfer'){
						curLead.Status_Explanation__c = 'Lead Gen Transfer corrected';
					}
					curLead.OwnerId = curLead.Former_Owner__c;
					leadsToUpdate.add(curLead);
				} 
				update leadsToUpdate;
		}
		catch(DmlException dmlEx)
		{
			System.debug('DML Exception thrown: ' + dmlEx.getMessage());
		}
		catch(Exception ex)
		{
			System.debug('Exception thrown: ' + ex.getMessage());
		}
	}	
	
	
	global void finish(Database.BatchableContext info){}		

} //class