prod_snapshot_2015-09-24_1030/objects/Market__c.object
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Market</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Yipit__c.object
<CustomObject>
    <fields>
        <fullName>Date_Ended__c</fullName>
        <label>Date Ended</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Yipits</relationshipLabel>
        <relationshipName>Yipits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Yipit</label>
    <nameField>
        <label>Yipit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Yipits</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Yipit_Market__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Yipit Markets</relationshipLabel>
        <relationshipName>Yipit_Markets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Yipit Market</label>
    <nameField>
        <label>Division</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Yipit Markets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/batchonYipit_updateMarket.cls
global class batchonYipit_updateMarket implements Database.Batchable<Yipit__c>{
	Date YipitLimit = date.today()-14;
	List<Yipit__c> YipsToUpdate = [SELECT Id, Division__c, Market__c FROM Yipit__c WHERE Date_Ended__c >= :YipitLimit limit 50000];
	List<Yipit_Market__c> YipMarks = [SELECT Id, Name, Market__c FROM Yipit_Market__c];
	global Iterable<Yipit__c> start(database.batchablecontext Yips){
		return (YipsToUpdate);
	}
	global void execute(Database.BatchableContext Yips, List<Yipit__c> scope){
		List<Yipit__c> YipsToLoad = new List<Yipit__c>();
		for(Yipit__c tempYip : scope){
			for(Yipit_Market__c tempYipMark : YipMarks){
				if(tempYipMark.Name == tempYip.Division__c){// && (tempYip.Market__c == Null || tempYip.Market__c != tempYipMark.Market__c)){}
					tempYip.Market__c = tempYipMark.Market__c;
					YipsToLoad.add(tempYip);
					//YipsToLoad.add((Yipit__c) tempYip);
				}
			}
		}
		upsert YipsToLoad;//upsert scope;
	}
global void finish(Database.BatchableContext info){}
}