prod_snapshot_2015-09-24_1030/objects/Opportunity_Product_History__c.object
<CustomObject>
    <description>History object used to track status changes in Opportunity Products</description>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>OLI_Stage__c</fullName>
        <label>OLI Stage</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Product_Type__c</fullName>
        <description>Type of product</description>
        <label>Opportunity Product Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Product__c</fullName>
        <label>Opportunity Product</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Product Histories</relationshipLabel>
        <relationshipName>Opportunity_Product_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_In__c</fullName>
        <label>Time_In</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Time_Out__c</fullName>
        <label>Time Out</label>
        <type>DateTime</type>
    </fields>
    <label>Opportunity Product History</label>
    <nameField>
        <displayFormat>SLA-{00000000}</displayFormat>
        <label>Opportunity Product History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>160</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opp_Product_Id__c</fullName>
        <formula>CASESAFEID(Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Product ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>PricebookEntry.Product2.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Waiting_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Onboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting On Client Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting On Client Resource</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hard Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Non-Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled-Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>--Internal Use Only--</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused:Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused:No Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Accessories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Art</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back to school</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bedding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car accessories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clothing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cookware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facebook Ads</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housewares</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>iPhone accessories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jewelry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile-Only Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outdoor supplies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pet Supplies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retargeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Ads</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Media Mgmt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Template Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toys</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Website</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/OpportunityProductReportController.cls
public class OpportunityProductReportController {
	
	public OpportunityLineItemChartServices oliChartServices {get; set;}
	
	public final String SOQL_EXECUTION_ERROR = 'There was an issue executing the SOQL Query. Please contact the Salesforce administrator. ';
	
	public static final SelectOption ALL_PRODUCT_STATUSES = new SelectOption('*', 'Status - All');
	public static final SelectOption ALL_PRODUCT_TYPES = new SelectOption('*', 'Type - All');
	
	public String selectedProductStatus {get; set;}
	public String selectedProductType {get; set;}
	public Date selectedStartDate {get; set;}
	public Date selectedEndDate {get; set;}
	public List<SelectOption> selectedProducts {get; set;}

	public OpportunityProductReportController(){
		
		this.oliChartServices = new OpportunityLineItemChartServices();
		
		this.selectedProductStatus = ALL_PRODUCT_STATUSES.getValue();
		this.selectedProducts = new List<SelectOption>();
	}
	
	public String chartDataJSON {
		get {
			system.debug('oliChartServices.chartDataJSON: ' + oliChartServices.chartDataJSON);
			return oliChartServices.chartDataJSON;
		}
		set;
	}
	public String dataFieldDepth {
		get {
			system.debug('oliChartServices.dataFieldDepth: '+ oliChartServices.dataFieldDepth);
			return oliChartServices.dataFieldDepth;
		}
		set;
	}
	

	
	public static List<SelectOption> getProductStatuses {
		get {
			List<SelectOption> options = new List<SelectOption>();
			options.add(ALL_PRODUCT_STATUSES);
			if (getProductStatuses == null){
				Schema.DescribeFieldResult F = OpportunityLineItem.Waiting_Status__c.getDescribe();
				List<Schema.PicklistEntry> stageNamesPickList = F.getPicklistValues();
				for (Schema.PicklistEntry stageEntry : stageNamesPickList){
					if (stageEntry.getLabel().contains('Internal Use Only')) break;
					options.add(new SelectOption(stageEntry.getValue(), stageEntry.getLabel()));
				}
				
			}
			return options; 
		}
		set;
		
	}
	
	public static List<SelectOption> getProductTypes {
		get {
			List<SelectOption> options = new List<SelectOption>();
			options.add(ALL_PRODUCT_TYPES);
			if (getProductTypes == null){
				Schema.DescribeFieldResult F = Product2.Product_Type__c.getDescribe();
				List<Schema.PicklistEntry> typeNamesPickList = F.getPicklistValues();
				for (Schema.PicklistEntry typeEntry : typeNamesPickList){
					options.add(new SelectOption(typeEntry.getValue(), typeEntry.getLabel()));
				}
				
			}
			return options; 
		}
		set;
		
	}
	
	
	public List<SelectOption> allProducts {
		get {
			List<SelectOption> options = new List<SelectOption>();
			if (allProducts == null){
				List<OpportunityLineItem> allOppProducts = [Select OpportunityId, Opp_Product_Id__c, Id, Product_Name__c 
															From OpportunityLineItem  ];
				for (OpportunityLineItem oppProduct : allOppProducts){
					options.add(new SelectOption(oppProduct.Opp_Product_Id__c, oppProduct.Product_Name__c));
				}
			}
			return options; 
		}
		set;
	}
	

	public List<Opportunity_Product_History__c> getOppProdHistResults {
		get {
			List<Opportunity_Product_History__c> results; 
			
			Set<String> selectedProductsIds = new Set<String>();
			for (SelectOption op : selectedProducts){
				selectedProductsIds.add(op.getValue());
			}
			
			system.debug('selectedProductsIds: '+ selectedProductsIds);
			system.debug('selectedProductStatus: '+ selectedProductStatus);
			
			String databaseQuery = 'Select Id, Opportunity__c, Opportunity_Product__c, Opportunity_Product_Type__c, ';
			databaseQuery +=	   		'OLI_Stage__c, Notes__c, ';
			databaseQuery +=	   		'Duration__c, Time_In__c, Time_Out__c ';
			databaseQuery +=		'From Opportunity_Product_History__c ';
			databaseQuery +=		'Where Opportunity_Product__c in :selectedProductsIds ';
			
			if (selectedProductStatus != ALL_PRODUCT_STATUSES.getValue()){
				databaseQuery += ' AND OLI_Stage__c = :selectedProductStatus ';
			}
			if (selectedProductType != ALL_PRODUCT_TYPES.getValue()){
				databaseQuery += ' AND Opportunity_Product_Type__c = :selectedProductType ';
			}
			if (selectedStartDate != null){
				databaseQuery += ' AND Time_In__c >= :selectedStartDate ';
			}
			if (selectedEndDate != null){
				databaseQuery += ' AND Time_Out__c <= :selectedEndDate ';
			}
			databaseQuery +=		' Order By Time_In__c ';
		
			try {
				results =  Database.query(databaseQuery);
			}
			catch (Exception e){
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, SOQL_EXECUTION_ERROR + e.getMessage()));
			}
			return results;
		}
		set;
	}	

	
	public void runReport() {
		
		this.oliChartServices = new OpportunityLineItemChartServices();
	
		Map<String, Integer> dataFieldIndex = new Map<String, Integer>(); 
		for (Opportunity_Product_History__c oppProdHist : getOppProdHistResults){
			OpportunityLineItemChartServices.OppProductHistoryRecord hRecord = new OpportunityLineItemChartServices.OppProductHistoryRecord(oppProdHist);
			String stage = oppProdHist.OLI_Stage__c != null ? hRecord.record.OLI_Stage__c : OpportunityLineItemServices.CREATED_STAGE_NAME;
			
			if (!dataFieldIndex.containsKey(stage)){
				dataFieldIndex.put(stage, 1);
			} 
			else {
				dataFieldIndex.put(stage, dataFieldIndex.get(stage)+1);
			}
			
			if (oliChartServices.chartDataMap.containsKey(stage)){
				oliChartServices.chartDataMap.get(stage).setDataPoint(dataFieldIndex.get(stage), hRecord.getDuration);
			}
		}
		
	}

	
}