prod_snapshot_2015-09-24_1030/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <description>Date of Account Standing Change</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Payment_Processing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Processing</label>
        <referenceTo>Payment_Processing__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Payment_Entries__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Book_Amount__c</fullName>
        <label>Book Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CC__c</fullName>
        <label>CC</label>
        <referenceTo>Payment_Processing__c</referenceTo>
        <relationshipLabel>Payment Entries</relationshipLabel>
        <relationshipName>Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Custom_Set__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Custom Set</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Declined__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Declined</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KPI_Calender__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI Calender</label>
        <referenceTo>KPICalender__c</referenceTo>
        <relationshipLabel>Payment Entries</relationshipLabel>
        <relationshipName>Payment_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Processor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Processor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Payment_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Set__c</fullName>
        <defaultValue>false</defaultValue>
        <label>System Set</label>
        <type>Checkbox</type>
    </fields>
    <label>Payment Entry</label>
    <nameField>
        <label>Entry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Payment_Processing__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Payment Processing</relationshipLabel>
        <relationshipName>Credit_Card_Processing</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment Processing</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>Credit Card Processing</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Processing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/OpportunityPaymentEntries.cls
/**
 *  @Class Name : OpportunityPaymentEntries
    Created By  : Vijaya Varada
    Descritpion : Creates Opportunity Products Payment Entries based Opportunity Products Schedule
    Modifed By  : N/A
 */
 
global with sharing class OpportunityPaymentEntries {
	
	webservice static string createPaymentEntries(Id oppLineItemId){
		try{
			updateOppPaymentProcessAndcreatePaymentEntries(oppLineItemId);
			return 'Success';
		}catch(exception ex)
        {
            return ex.getMessage();
        }
	}
	
	//Create Payment Entries Based on Criteria 
	private static void updateOppPaymentProcessAndcreatePaymentEntries(Id oppLineItemId){
		//If Logged in User is not same as Gannet Local User
		if (UserInfo.GetUserId() != Constants.GANNETT_LOCAL_USER.Id){
			List<OpportunityLineItem> oppLineItems = [Select Id, Payment_Processing__c, OpportunityId 
														from OpportunityLineItem Where Id =: oppLineItemId];
			
			OpportunityLineItem oneOppLineItem;		
			Payment_Processing__c onePaymentProcessing;				
								
			if(oppLineItems != null && oppLineItems.size()>0){
				oneOppLineItem = oppLineItems[0];
				List<Payment_Processing__c> oppPaymentProcessings = [SELECT Id, Name FROM Payment_Processing__c 
			 								 						  WHERE Opportunity__c =: oppLineItems[0].OpportunityId];
				if(oppPaymentProcessings != null && oppPaymentProcessings.size()>0){
					onePaymentProcessing = oppPaymentProcessings[0];
				}			 								 						  
			}
			
			if(oneOppLineItem != null && onePaymentProcessing != null){
				oneOppLineItem.Payment_Processing__c = onePaymentProcessing.Id;
				update oneOppLineItem;
				createPaymentEntriesforOpportunityLineItemSchedules(oneOppLineItem, onePaymentProcessing);
			}			
		}
	}
	
	//Create Payment Entries for Opportunity Line Item Schedules
    private static void createPaymentEntriesforOpportunityLineItemSchedules(OpportunityLineItem oneOppLineItem, Payment_Processing__c onePaymentProcessing){
		//Opportunity Payment Entries that needs to be inserted
        Map<Date, Payment_Entries__c> mapOppPaymentEntries = new Map<Date, Payment_Entries__c>();    																   	
    	Date minDate;
    	//If Logged in User is not same as Gannet Local User
		if (UserInfo.GetUserId() != Constants.GANNETT_LOCAL_USER.Id 
			&& oneOppLineItem != null && onePaymentProcessing != null){
				
			 List<OpportunityLineItemSchedule> listOppLineItemSchedules
			 						 = [SELECT Id, ScheduleDate, Revenue, OpportunityLineItemId 
 										 FROM OpportunityLineItemSchedule
 									   	 WHERE OpportunityLineItemId in (Select Id from OpportunityLineItem 
 										 		Where OpportunityId =: oneOppLineItem.OpportunityId)
 										 ORDER BY ScheduleDate];
 										 								
			 for(OpportunityLineItemSchedule oneOppLineItemSchedule : listOppLineItemSchedules){
		 		Payment_Entries__c newPaymentEntry = mapOppPaymentEntries.get(oneOppLineItemSchedule.ScheduleDate);
				if(newPaymentEntry == null){
					newPaymentEntry = new Payment_Entries__c();
			 		newPaymentEntry.CC__c = onePaymentProcessing.Id;
			 		newPaymentEntry.Name = onePaymentProcessing.Name + '-' + mapOppPaymentEntries.size();
			 		newPaymentEntry.Date__c = oneOppLineItemSchedule.ScheduleDate; 
			 		newPaymentEntry.Amount__c = oneOppLineItemSchedule.Revenue;
			 		newPaymentEntry.Custom_Set__c = true;
			 		newPaymentEntry.Processor__c = Constants.SALESFORCE_ADMINISTRATION.Id;
			 		newPaymentEntry.System_Set__c = false;
			 		newPaymentEntry.KPI_Calender__c = Constants.KPI_CAL_20111226.Id;
			 		if(minDate!=null && minDate > oneOppLineItemSchedule.ScheduleDate){
			 			minDate = oneOppLineItemSchedule.ScheduleDate;
			 		}else if(minDate==null){
			 			minDate = oneOppLineItemSchedule.ScheduleDate;
			 		}
			 		mapOppPaymentEntries.put(oneOppLineItemSchedule.ScheduleDate, newPaymentEntry);	
				}else{
					newPaymentEntry.Amount__c = newPaymentEntry.Amount__c + oneOppLineItemSchedule.Revenue;
				}
			 }
		
		
		 	System.debug('mapOppPaymentEntries >> ' + mapOppPaymentEntries) ;
			List<Payment_Entries__c> deletePaymentEntries = [Select Id from Payment_Entries__c
																where CC__c in (Select Id from Payment_Processing__c 
																	where Opportunity__c =: oneOppLineItem.OpportunityId)
																and Completed__c = false and Declined__c = false];
            if(deletePaymentEntries.size()>0){
            	delete deletePaymentEntries;
            }
	            
	        if(mapOppPaymentEntries.size() >0){
			    //The very first item in the map will have book amont because the map is sorted by ScheduleDate in SOQL
	            Payment_Entries__c firstPaymentEntry = mapOppPaymentEntries.get(minDate);
	            firstPaymentEntry.Book_Amount__c = firstPaymentEntry.Amount__c;
	            insert mapOppPaymentEntries.Values();
			}
		}
    }
}