prod_snapshot_2015-09-24_1030/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>CancelType__c</fullName>
        <label>Type of Cancel</label>
        <picklist>
            <picklistValues>
                <fullName>Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hard Cancel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cancellation_Category__c</fullName>
        <label>Cancellation Category</label>
        <picklist>
            <picklistValues>
                <fullName>Cancelled Before Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled After Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Non-Renewal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cancellation_Detail__c</fullName>
        <description>This Picklist has the sub category for the  cancellation reasons.</description>
        <label>Cancellation Detail</label>
        <picklist>
            <controllingField>Cancellation_Reason__c</controllingField>
            <picklistValues>
                <fullName>Sold outside of deliverables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Set unrealistic or no performance expectations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client not fully explained OB process, frustrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Undersold vs recommendation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wrong product for the client’s goals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales communicated ‘opt out period’ to client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No reason provided from affiliate rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cannot pay/No budget/Business Closing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unrealistic expectations, never able to change, not enough time to prioritize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seasonality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moving marketing in house</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client refused to give explanation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received better pricing from competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New ‘decision maker’ unwilling to continue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lack of communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Responsiveness/Timeliness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client issue unresolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low Performance/Lack of, or irrelevant leads</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work quality issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Over/Under Spend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed deadline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social: posts never change, eventually lose value</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Platform issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client billed incorrect amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client billed twice in one period</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client unhappy with billing procedure (pause policy)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entire spend moved to another G/O product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product down sell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product up sell</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cancellation_Reason__c</fullName>
        <label>Cancellation Reason</label>
        <picklist>
            <controllingField>Cancellation_Category__c</controllingField>
            <picklistValues>
                <fullName>Sales Expectation Mismatch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G/O Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Business Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Unresponsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reallocation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Non Renewal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Invoice_CancelDate__c</fullName>
        <label>Invoice Cancel Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_ServiceEndDate__c</fullName>
        <label>Product End of Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_ServiceStartDate__c</fullName>
        <label>Product Start of Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Waiting_Status_Descr__c</fullName>
        <label>Status Descr/Notes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Waiting_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Onboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting On Client Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting On Client Resource</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hard Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Non-Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled-Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>--Internal Use Only--</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused:Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused:No Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/OpportunityLineItemUSCPCancelController.cls
public class OpportunityLineItemUSCPCancelController {
    
    public OpportunityLineItem oli{set;get;}
    public OpportunityLineItemUSCPCancelController(ApexPages.StandardController stdController) {
        
        oli = (OpportunityLineItem) stdController.getRecord();
        oli = [SELECT Id, Invoice_ServiceEndDate__c, Invoice_ServiceStartDate__c, 
                                           CancelType__c, Waiting_Status__c,
                                           Cancellation_Category__c, Cancellation_Reason__c,
                                           Invoice_CancelDate__c,Waiting_Status_Descr__c,Cancellation_Detail__c
                               FROM OpportunityLineItem
                                WHERE Id =: oli.Id];
   
    }
    
    public PageReference save()
    {
        PageReference ref = new PageReference('/apex/OpportunityLineItemUSCP?id='+oli.id);
      try
        {
            String errMsg = 'Please select Cancellation Detail';
            if(oli.Cancellation_Reason__c != null && oli.Cancellation_Detail__c == null)
            {
              ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,errMsg));
              ref = null;  
            }
            else
            {
             update oli;   
            }  
        }
        catch(DmlException ex){
           System.debug('Update OLI exception details from OpportunityLineItemUSCPCancelController Controller >> ' + ex);
           if(ex.getDmlStatusCode(0) !=null && ex.getDmlFields(0) == null){
             ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getDmlMessage(0)));
           }
           ref = null;
        }
        
      return ref;  
    }
    Public PageREference cancel()
    {
        PageReference ref = new PageReference('/apex/OpportunityLineItemUSCP?id='+oli.id);  
      return ref;
    }
    
}