prod_snapshot_2015-09-24_1030/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_PorC_Date__c</fullName>
        <description>Earliest Opportunity Product PorC date which caused the current PorC state on the opportunity</description>
        <label>Opportunity P or C Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Waiting_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Onboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting On Client Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting On Client Resource</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hard Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Non-Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled-Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>--Internal Use Only--</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused:Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused:No Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/OppPORCUpdate.cls
public class OppPORCUpdate{
// Code to update the PORC Date
	public static set<ID> processedOLIPorCChanges = new set<ID>(); // Will be referenced by different runs of this class in a single transaction.
	
    public static List<Opportunity> calcPORCDate(List<OpportunityLineItem> listOpportunityLineItems) {
        List<Opportunity> lineItemParentRecords =   new List<Opportunity>();
        List<OpportunityLineItem> listLineItems =   new List<OpportunityLineItem>();
        Set<String> parentIds   =   new Set<String>();
        
        for (integer i=0;i<listOpportunityLineItems.size();i++){
        	//Remove any OLI that have already had a status update this transaction.
        	if (!processedOLIPorCChanges.isempty() && processedOLIPorCChanges.contains(listOpportunityLineItems[i].ID)){
				continue;
			}
            if(listOpportunityLineItems[i].OpportunityId != null ) {
                parentIds.add(listOpportunityLineItems[i].OpportunityId);
            }
        }
        
        if (parentIds.size()>0)
        {
            lineItemParentRecords   =   [SELECT Id, Opportunity_PorC_Date__c FROM Opportunity WHERE Id IN :parentIds];
            listLineItems   =   [SELECT Id, Waiting_Status__c,OpportunityId  FROM OpportunityLineItem WHERE OpportunityId IN :lineItemParentREcords];
            for(Opportunity objOpportunity : lineItemParentRecords) {
                for(OpportunityLineItem objLineItem : listLineItems) {
                    if(objLineItem.OpportunityId == objOpportunity.Id) {
                        if(objLineItem.Waiting_Status__c == 'Cancelled' || objLineItem.Waiting_Status__c == 'Hard Cancel' || objLineItem.Waiting_Status__c == 'Paused:Billing' || objLineItem.Waiting_Status__c == 'Paused:No Contact') {
                            if(objOpportunity.Opportunity_PorC_Date__c == null ){
                                objOpportunity.Opportunity_PorC_Date__c = System.today();
                                processedOLIPorCChanges.add(objLineItem.Id);
                            }
                            break;
                        } else {
                            if(objOpportunity.Opportunity_PorC_Date__c == null){
                                processedOLIPorCChanges.add(objLineItem.Id);
                            }
                            else{
                                objOpportunity.Opportunity_PorC_Date__c = null;
                            }
                        } 
                    }
                }
            }
            
            //Prevent further POC Date updates for associated OLI in this transaction
            // Commented for updating date after workflow updatation
            //processedOLIPorCChanges.addall(new map<id,opportunityLineItem>(listLineItems).keyset());
        }
		return lineItemParentRecords;
    }
}