prod_snapshot_2015-09-24_1030/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Affl_Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Affl Sales Rep</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Affiliated_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cancellation_Category__c</fullName>
        <label>Cancellation Category</label>
        <picklist>
            <picklistValues>
                <fullName>Cancelled Before Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled After Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Non-Renewal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cancellation_Reason__c</fullName>
        <label>Cancellation Reason</label>
        <picklist>
            <controllingField>Cancellation_Category__c</controllingField>
            <picklistValues>
                <fullName>Sales Expectation Mismatch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G/O Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Business Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Unresponsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reallocation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Non Renewal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Dig_Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dig Account Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Dig_AM_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email_Recipients_Qty__c</fullName>
        <description>SR-2867/DEV-962: Jumpstart and Finance users need the ability to see, edit and report on this information</description>
        <label>Email - Recipients Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice_CancelDate__c</fullName>
        <label>Invoice Cancel Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_CancelFeePercent__c</fullName>
        <label>Cancellation Fee Percent</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Invoice_ServiceEndDate__c</fullName>
        <label>Product End of Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_ServiceStartDate__c</fullName>
        <label>Product Start of Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mgmt_Fee_Percent__c</fullName>
        <description>The Finance and Operations Teams need a way for the Jumpstart Team to code PPC Management Fee when it is put in as a product.</description>
        <label>Mgmt Fee %</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Notify_Email_1__c</fullName>
        <label>Notify Email 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Notify_Email_2__c</fullName>
        <label>Notify Email 2</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Notify_Email_3__c</fullName>
        <label>Notify Email 3</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>NumberOfHours__c</fullName>
        <label>Number Of Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NumberOfLocations__c</fullName>
        <label>Number Of Locations</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opp_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Rep_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Qty_ContractMonths__c</fullName>
        <label>Number of Contract Months</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Qty_LineItems__c</fullName>
        <label>Number of Line Items</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <description>Opportunity Record type Name</description>
        <label>Record Type Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReferenceID_OriginalNewSell__c</fullName>
        <label>Original NewSell OLI ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sell_Type__c</fullName>
        <label>Sell Type</label>
        <picklist>
            <picklistValues>
                <fullName>NewSell</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>UpSell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CrossSell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Extension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DownSell</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Waiting_Status_Descr__c</fullName>
        <label>Status Descr/Notes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Waiting_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Onboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting On Client Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting On Client Resource</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hard Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Non-Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled-Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>--Internal Use Only--</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused:Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused:No Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/UpdateAgreementCntrl.cls
public class UpdateAgreementCntrl {
    private OpportunityLineItem oliRecord;
	/*public OpportunityLineItem oli {
		set;
		get;
	}
	public OpportunityLineItem olistd {
		set;
		get;
	}*/
	public String sellType {
		set;
		get;
	}
	
	public UpdateAgreementCntrl(ApexPages.StandardController stdController) {
		oliRecord = (OpportunityLineItem) stdController.getRecord();
		oliRecord.Qty_ContractMonths__c = 4;
	}
	
	public PageReference save() {
		OpportunityLineItem existingOLI = [SELECT Id, Waiting_Status__c,
												Record_Type_Name__c,
												Discount, OpportunityId,
												Description, Product2ID, ProductCode, Name, UnitPrice,
												Opp_Owner__c, Qty_ContractMonths__c,
												Dig_Account_Manager__c,
												Affl_Sales_Rep__c,
												Notify_Email_1__c,
												Notify_Email_2__c,
												Notify_Email_3__c,
												ServiceDate,
												PricebookEntryId,
												Quantity,
												Cancellation_Category__c,
												Cancellation_Reason__c,
												Sell_Type__c,
												Invoice_CancelDate__c,
												Waiting_Status_Descr__c,
												NumberOfLocations__c, NumberOfHours__c, Invoice_ServiceStartDate__c, Invoice_ServiceEndDate__c, Invoice_CancelFeePercent__c,
												Qty_LineItems__c, Email_Recipients_Qty__c, Mgmt_Fee_Percent__c
											FROM OpportunityLineItem WHERE Id = : oliRecord.Id];
		 
		OpportunityLineItem newOLI = new OpportunityLineItem();

		newOLI.Record_Type_Name__c = existingOLI.Record_Type_Name__c;
		newOLI.Waiting_Status__c = 'Closed Won';
		newOLI.Discount = existingOLI.Discount;
		newOLI.Description = existingOLI.Description;
		newOLI.PricebookEntryId = existingOLI.PricebookEntryId;
		//retrieving Qty_ContractMonths__c from controller oli record
		newOLI.Qty_ContractMonths__c = oliRecord.Qty_ContractMonths__c;
		//newOLI.Quantity = existingOLI.Quantity;
		newOLI.OpportunityId = existingOLI.OpportunityId;
		newOLI.UnitPrice = existingOLI.UnitPrice;
		newOLI.Opp_Owner__c = existingOLI.Opp_Owner__c;
		newOLI.Dig_Account_Manager__c = existingOLI.Dig_Account_Manager__c;
		newOLI.Affl_Sales_Rep__c = existingOLI.Affl_Sales_Rep__c;
		newOLI.Notify_Email_1__c = existingOLI.Notify_Email_1__c;
		newOLI.Notify_Email_2__c = existingOLI.Notify_Email_2__c;
		newOLI.Notify_Email_3__c = existingOLI.Notify_Email_3__c;
		newOLI.Mgmt_Fee_Percent__c = existingOLI.Mgmt_Fee_Percent__c;
		newOLI.Email_Recipients_Qty__c = existingOLI.Email_Recipients_Qty__c;
		newOLI.Qty_LineItems__c = existingOLI.Qty_LineItems__c;
		newOLI.Invoice_CancelFeePercent__c = existingOLI.Invoice_CancelFeePercent__c;
		
		if (existingOLI.Invoice_ServiceStartDate__c != null) {
			newOLI.Invoice_ServiceStartDate__c = existingOLI.Invoice_ServiceEndDate__c.addDays(1);
			newOLI.Invoice_ServiceEndDate__c = newOLI.Invoice_ServiceStartDate__c.addMonths(Integer.ValueOf(newOLI.Qty_ContractMonths__c));
		}
		
		newOLI.ServiceDate = existingOLI.ServiceDate;
		newOLI.ReferenceID_OriginalNewSell__c = existingOLI.id;
		newOLI.NumberOfHours__c = existingOLI.NumberOfHours__c;
		newOLI.NumberOfLocations__c = existingOLI.NumberOfLocations__c;
		existingOLI.Waiting_Status__c = 'Fulfilled Renewed';
		
        if (sellType != 'None') {
			newOLI.Sell_Type__c = sellType;
		}
			
		
		PageReference ref;
		try {
				if(sellType == 'None'){
            	String errMsg = 'Please select a Sell Type';
            	ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,errMsg));
            	ref = null;
        		}
            	else{            
				
				insert newOLI;
				update existingOLI;
				ref = new PageReference('/apex/OpportunityLineItemUSCP?id=' + newOLI.Id);
            	}
			} 
        catch (DmlException ex) 
        	{
			System.debug('Update OLI exception details from OpportunityLineItemUSCPCancelController Controller >> ' + ex);
			if (ex.getDmlStatusCode(0) != null && ex.getDmlFields(0) == null) {
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getDmlMessage(0)));
			}
			ref = null;
		}

		return ref;
	}


	public PageReference cancel() {
		PageReference ref = new PageReference('/apex/OpportunityLineItemUSCP?id=' + oliRecord.Id);

		return ref;
	}

}