prod_snapshot_2015-09-24_1030/objects/Opportunity_Product_History__c.object
<CustomObject>
    <description>History object used to track status changes in Opportunity Products</description>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>OLI_Stage__c</fullName>
        <label>OLI Stage</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Product__c</fullName>
        <label>Opportunity Product</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Product Histories</relationshipLabel>
        <relationshipName>Opportunity_Product_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_In__c</fullName>
        <label>Time_In</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Time_Out__c</fullName>
        <label>Time Out</label>
        <type>DateTime</type>
    </fields>
    <label>Opportunity Product History</label>
    <nameField>
        <displayFormat>SLA-{00000000}</displayFormat>
        <label>Opportunity Product History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>160</length>
        <type>Text</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/OppLineItemCntrl.cls
public class OppLineItemCntrl {
    
   public ApexPages.StandardController theController;
    
    public OpportunityLineItem oli {get;set;}
   // public OpportunityLineItemChartServices oliChartServices {get; set;}
    
    //public List<Opportunity_Product_History__c> HistoryTrack {get; set;}
   // public List<OpportunityLineItemChartServices.OppProductHistoryRecord> HistoryTrackRecords {get; set;}
    
    public OppLineItemCntrl(ApexPages.StandardController stdController) {
        
         OpportunityLineItem controllerOli = (OpportunityLineItem)stdController.getRecord(); 
        /*this.oli = [Select Id From OpportunityLineItem Where Id = :controllerOli.ID];
        
        this.oliChartServices = new OpportunityLineItemChartServices();
        
        this.HistoryTrackRecords = new List<OpportunityLineItemChartServices.OppProductHistoryRecord>();
        this.HistoryTrack = [Select     Id, 
                                        Opportunity__c, 
                                        Opportunity_Product__c, 
                                        OLI_Stage__c, 
                                        Notes__c,
                                        Duration__c, 
                                        Time_In__c, 
                                        Time_Out__c,
                                        CreatedBy.Name,
                                        LastModifiedBy.Name
                            From Opportunity_Product_History__c 
                            Where Opportunity_Product__c = :controllerOli.Id 
                            Order By Time_In__c];
        
        Map<String, Integer> dataFieldIndex = new Map<String, Integer>(); 
        
        Integer i = 0;
        for (Opportunity_Product_History__c oppProdHist : HistoryTrack){
            OpportunityLineItemChartServices.OppProductHistoryRecord hRecord = new OpportunityLineItemChartServices.OppProductHistoryRecord(oppProdHist);
            
            String stage = hRecord.record.OLI_Stage__c != null ? hRecord.record.OLI_Stage__c : OpportunityLineItemServices.CREATED_STAGE_NAME;

            hRecord.backtrack = false;
            
            hRecord.orderOfOccurence = ++i;

            if (!dataFieldIndex.containsKey(stage)){
                dataFieldIndex.put(stage, 1);
            } 
            else {
                dataFieldIndex.put(stage, dataFieldIndex.get(stage)+1);
                hRecord.backtrack = true;
            }
            
           if (oliChartServices.chartDataMap.containsKey(stage)){
                oliChartServices.chartDataMap.get(stage).setDataPoint(dataFieldIndex.get(stage), hRecord.getDuration);
            }
            
            HistoryTrackRecords.add(hRecord);
        } */
    }
    
   
}