prod_snapshot_2015-09-24_1030/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Include_Address_in_Ads__c</fullName>
        <inlineHelpText>Choose whether or not the Company address needs to be included in advertising for this Opportunity. Most customers without actual store fronts choose not to include their address.</inlineHelpText>
        <label>Include Address in Ads</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>SML_Opportunity</fullName>
        <active>true</active>
        <businessProcess>Acquisition</businessProcess>
        <label>SML Opportunity</label>
    </recordTypes>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Payment_Entries__c.object
<CustomObject>
    <fields>
        <fullName>CC__c</fullName>
        <label>CC</label>
        <referenceTo>Payment_Processing__c</referenceTo>
        <relationshipLabel>Payment Entries</relationshipLabel>
        <relationshipName>Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment Entry</label>
    <nameField>
        <label>Entry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Payment_Processing__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Options__c</fullName>
        <label>Billing Options</label>
        <picklist>
            <picklistValues>
                <fullName>Bill Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Total</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice/Credit Terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Memo Bill</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Number__c</fullName>
        <inlineHelpText>Enter numbers only, no dashes</inlineHelpText>
        <label>Credit Card #1 Number</label>
        <length>16</length>
        <maskChar>asterisk</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Type__c</fullName>
        <label>Credit Card #1 Type</label>
        <picklist>
            <picklistValues>
                <fullName>Visa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mastercard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Express</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cycles__c</fullName>
        <label>Cycles</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>Date After Which Charges Will No Longer Be Applied.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entry_Cycle__c</fullName>
        <label>Entry Cycle</label>
        <picklist>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Entry_Processor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entry Processor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Payment_Processing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exp_Month__c</fullName>
        <label>Card #1 Exp Month</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Exp_Year__c</fullName>
        <label>Card #1 Exp Year</label>
        <picklist>
            <picklistValues>
                <fullName>2009</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>First_Charge_Day__c</fullName>
        <label>First Charge Day</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Payment Processing</relationshipLabel>
        <relationshipName>Credit_Card_Processing</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reset_Entries__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reset Entries</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Security_Code__c</fullName>
        <label>Card #1 Security Code</label>
        <length>4</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <label>Payment Processing</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>Credit Card Processing</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Processing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/beforeonPaymentProcess_class.cls
// <PWP> Class name implies it's a class, not a test

/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class beforeonPaymentProcess_class {
	// <refactor>  Class name implies it's a class, not a test

    static testMethod void testPaymentProcessing1() {
    	
    	// <refactor> test data creation utility should be used to create test data 
        Opportunity Test1Opp = new Opportunity(RecordTypeId = RecordTypeCache.getRecordType('Opportunity', 'SML_Opportunity').id,
        									   AccountId = Constants.GO_DIGITAL_COMPANY.Id,
        									   Name = 'TestOppForPPEntries',
        									   Type = 'New Business',
        									   Include_Address_in_Ads__c = 'Yes',
        									   StageName = 'Needs Analysis',
        									   CloseDate = date.today(),
        									   Amount = 100);
        // <refactor> unnecessary debug statements 
        system.debug('Before inserting Opp');
        insert Test1Opp;  	
        system.debug('After inserting Opp');
        
        // <refactor> test data creation utility should be used to create test data 
        Payment_Processing__c Test1PP = new Payment_Processing__c(Opportunity__c = Test1Opp.Id,
        														  Credit_Card_Type__c = 'Mastercard',
        														  Credit_Card_Number__c = '4444555566667777',
        														  Exp_Month__c = '8',
        														  Exp_Year__c = '2011',
        														  Security_Code__c = '666',
        														  Billing_Options__c = 'Bill Monthly',
        														  Entry_Processor__c = Constants.GANNETT_LOCAL_USER.Id);
        // <refactor> unnecessary debug statements 
        system.debug('Before inserting PP');
        insert Test1PP;
        system.debug('After inserting PP');
        
        // <refactor> test data creation utility should be used to create test data 
        Payment_Processing__c  testPPAfter = [SELECT Id, First_Charge_Day__c, Entry_Cycle__c, Cycles__c, Reset_Entries__c
        									  FROM Payment_Processing__c
        									  WHERE Id = :Test1PP.Id];
         
		testPPAfter.First_Charge_Day__c = date.today() - 3;
		testPPAfter.Entry_Cycle__c = 'Monthly';
		testPPAfter.Cycles__c = '1';
		testPPAfter.Reset_Entries__c = True;
		
		// <refactor> use Test.startTest; test.stopTest to reset limits on specific blocks of code
		update testPPAfter;
		
		Integer testPEAfter = [SELECT count() from Payment_Entries__c WHERE CC__c = :testPPAfter.Id];
		
		// <refactor> needs an errror message to describe the problem
		System.assertEquals(1, testPEAfter);
    }
    static testMethod void testPaymentProcessing2() {
    	
    	// <refactor> test data creation utility should be used to create test data 
        Opportunity Test2Opp = new Opportunity(RecordTypeId = RecordTypeCache.getRecordType('Opportunity', 'SML_Opportunity').id,
        									   AccountId = Constants.GO_DIGITAL_COMPANY.id,
        									   Name = 'TestOppForPPEntries',
        									   Type = 'New Business',
        									   Include_Address_in_Ads__c = 'Yes',
        									   StageName = 'Needs Analysis',
        									   CloseDate = date.today(),
        									   Amount = 100);
        insert Test2Opp;  	
        
        // <refactor> test data creation utility should be used to create test data 
        Payment_Processing__c Test2PP = new Payment_Processing__c(Opportunity__c = Test2Opp.Id,
        														  Credit_Card_Type__c = 'Mastercard',
        														  Credit_Card_Number__c = '4444555566667777',
        														  Exp_Month__c = '8',
        														  Exp_Year__c = '2011',
        														  Security_Code__c = '666',
        														  Billing_Options__c = 'Bill Monthly',
        														  Entry_Processor__c = Constants.GANNETT_LOCAL_USER.Id);
        insert Test2PP;
        
        // <refactor> test data creation utility should be used to create test data 
        Payment_Processing__c  test2PPAfter = [SELECT Id,
        											  First_Charge_Day__c,
        											  End_Date__c,
        											  Entry_Cycle__c,
        											  Cycles__c,
        											  Reset_Entries__c
        									   FROM Payment_Processing__c
        									   WHERE Id = :Test2PP.Id];
        
        Date endDay = date.today();
        endDay = endDay.addDays(70);
		test2PPAfter.First_Charge_Day__c = date.today();
		test2PPAfter.End_Date__c = endDay;
		test2PPAfter.Entry_Cycle__c = 'Monthly';
		test2PPAfter.Reset_Entries__c = True;
		
		// <refactor> use Test.startTest; test.stopTest to reset limits on specific blocks of code
		update test2PPAfter;
		
		Integer test2PEAfter = [SELECT count() from Payment_Entries__c WHERE CC__c = :test2PPAfter.Id];
		
		// <refactor> needs an errror message to describe the problem
		System.assertEquals(3, test2PEAfter);
    }
}