prod_snapshot_2015-09-24_1030/objects/Opportunity_Product_History__c.object
<CustomObject>
    <description>History object used to track status changes in Opportunity Products</description>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OLI_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OLI Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunity Product Histories</relationshipLabel>
        <relationshipName>Opportunity_Product_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OLI_Stage__c</fullName>
        <label>OLI Stage</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Product__c</fullName>
        <label>Opportunity Product</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Product Histories</relationshipLabel>
        <relationshipName>Opportunity_Product_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_In__c</fullName>
        <label>Time_In</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Time_Out__c</fullName>
        <label>Time Out</label>
        <type>DateTime</type>
    </fields>
    <label>Opportunity Product History</label>
    <nameField>
        <displayFormat>SLA-{00000000}</displayFormat>
        <label>Opportunity Product History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Live_Date__c</fullName>
        <label>Live Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Waiting_Status_Descr__c</fullName>
        <label>Status Descr/Notes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Waiting_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Onboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting On Client Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting On Client Resource</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hard Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Non-Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled-Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>--Internal Use Only--</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused:Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused:No Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Product_SLA__c.object
<CustomObject>
    <description>Summaries the duration an Opportunity Product has spent on different stages.</description>
    <fields>
        <fullName>Live_Date__c</fullName>
        <description>The live date as per the related Opportunity Product record.</description>
        <inlineHelpText>The live date as per the related Opportunity Product record.</inlineHelpText>
        <label>Live Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opportunity_Product__c</fullName>
        <description>The 18 character ID of the related Opportunity Product.  Is unique and mandatory for a Product SLA record to be saved.</description>
        <inlineHelpText>The 18 character ID of the related Opportunity Product.  Is unique and mandatory for a Product SLA record to be saved.</inlineHelpText>
        <label>Opportunity Product</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>SLA</relationshipLabel>
        <relationshipName>SLA</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product SLA</label>
    <nameField>
        <label>Product SLA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product SLA</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/SLA_Related_Filters__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Holds information relevant to the search and display of the SLA Summary Report VF Page, and to the updates in batchProductSLARecalc</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether the record should be considered or not during the filtering processes.  Needs to be reset for the BatchProductSLARecalculation before every run.</description>
        <inlineHelpText>Whether the record should be considered or not during the filtering processes.  Needs to be reset for the BatchProductSLARecalculation before every run.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Live_After__c</fullName>
        <description>Only include Opportunity Products that went live after this date.</description>
        <inlineHelpText>Only include Opportunity Products that went live after this date.</inlineHelpText>
        <label>Live After</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Live_Before__c</fullName>
        <description>Only include Opportunity Products that went live before this date.</description>
        <inlineHelpText>Only include Opportunity Products that went live before this date.</inlineHelpText>
        <label>Live Before</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Live_Status__c</fullName>
        <description>A list of status&apos; that contribute to Live. These should also set the live date. Comma Separated.</description>
        <inlineHelpText>A list of status&apos; that contribute to Live. These should also set the live date. Comma Separated.</inlineHelpText>
        <label>Live Status</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Product_Created_After__c</fullName>
        <description>Process Opportunity Products created after this date. Date in this field should be on or after 12/8/2013, since that&apos;s when the Opportunity Product History object started gathering data.</description>
        <inlineHelpText>Process Opportunity Products created after this date. Date in this field should be on or after 12/8/2013, since that&apos;s when the Opportunity Product History object started gathering data.</inlineHelpText>
        <label>Opportunity Product Created After</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_Product_Created_Before__c</fullName>
        <description>Process Opportunity Products created before this date. Date in this field should be after 12/8/2013, since that&apos;s when the Opportunity Product History object started gathering data.</description>
        <inlineHelpText>Process Opportunity Products created before this date. Date in this field should be after 12/8/2013, since that&apos;s when the Opportunity Product History object started gathering data.</inlineHelpText>
        <label>Opportunity Product Created Before</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Filters__c</fullName>
        <description>SLA Products Types excluded for the SLA Summary Report / Product IDs included for updates in batchProductSLARecalc</description>
        <inlineHelpText>SLA Products Types excluded for the SLA Summary Report / Product IDs included for updates in batchProductSLARecalc</inlineHelpText>
        <label>Product Filters</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SLA Related Filters</label>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/BatchProductSLARecalculationTest.cls
@isTest(seeAllData=true)
public with sharing class BatchProductSLARecalculationTest {
	public static Account[] accounts {get;set;}
    public static Opportunity[] opportunities {get;set;}
    public static product2 product {get;set;}
    public static PriceBookEntry pricebookEntry {get;set;}
    public static OpportunityLineItem[] opportunityLineItems {get;set;}
    public static Opportunity_Product_History__c[] manualHistRecords {get;set;}
    public static datetime LastOutTime{get;set;}
	public static product_SLA__c[] ProductSLAs {get;set;}
	
	public static testMethod void testBatchProductSLARecalc(){
		populateOLIRelatedData(1,1,1);
		createOppProdHist(true);
		SET<ID> OLISet = new map<ID,OpportunityLineItem>(opportunityLineItems).keyset();
		string query = 'Select id from OpportunityLineItem where ID in (\'';
		query += String.join(new List<ID>(OLISet), '\',\'');	
		query += '\')';	
		system.debug('Passing query: ' + query);
		integer batchsize = 10;
		
		list<SLA_Related_Filters__c> filterSettingsList = [	SELECT 	Live_After__c, 
																	Live_Before__c,
																	Live_Status__c,
																	Opportunity_Product_Created_After__c,
																	Opportunity_Product_Created_Before__c,
																	Product_Filters__c,
																	Is_Active__c
															 FROM SLA_Related_Filters__c
															 WHERE Name = 'BatchProductSLARecalculationFilters'];
															 
		system.assertEquals(filterSettingsList.size(),1,'BatchProductSLARecalculationTest.testBatchProductSLARecalc: We expect to find a record in the custom settings for the batch job.');
		filterSettingsList[0].Live_After__c = LastOutTime.date(); 
		filterSettingsList[0].Live_Before__c = null;
		filterSettingsList[0].Live_Status__c = 'Live';
		filterSettingsList[0].Opportunity_Product_Created_After__c = date.newInstance(2013,12,08);
		filterSettingsList[0].Opportunity_Product_Created_Before__c = null;
		filterSettingsList[0].Product_Filters__c = product.ID;
		filterSettingsList[0].Is_Active__c = true;
		update filterSettingsList;
		OpportunityLineItemServices.processedOLIStatusChanges.clear();
		
		test.startTest();
		batchProductSLARecalculation processSLAusingQuery = new batchProductSLARecalculation(query);
		Database.QueryLocator ql = processSLAusingQuery.start(null);
		processSLAusingQuery.execute(null,opportunityLineItems);
		processSLAusingQuery.finish(null);		
		//ID qBatchExecuteID = Database.executeBatch(processSLAusingQuery,batchsize);
		system.debug('Finished executing the batch with Query:' + query);
        if (!ProductSLAs.isEmpty()){
			ProductSLAs.Clear();
         }
		ProductSLAs = [SELECT ID FROM Product_SLA__c where Opportunity_Product__c in :OLISet];
		system.debug('ProductSLAs: ' + ProductSLAs);
		system.assertEquals (OLISet.size(),ProductSLAs.size(),'BatchProductSLARecalculationTest.testBatchProductSLARecalc: We expect Product SLAs to be created when batchProductSLARecalculation is called with it\'s associated ID');
		 if (!ProductSLAs.isEmpty()){
             delete ProductSLAs;
         }
		OpportunityLineItemServices.processedOLIStatusChanges.clear();
		
		batchProductSLARecalculation processSLAusingCustomSettings = new batchProductSLARecalculation();
		ql = processSLAusingCustomSettings.start(null);
		processSLAusingCustomSettings.execute(null,opportunityLineItems);
		processSLAusingCustomSettings.finish(null);		
		//ID csBatchExecuteID = Database.executeBatch(processSLAusingCustomSettings,batchsize);
		system.debug('Finished executing the batch with custom settings.' );//+ csBatchExecuteID);
		test.stopTest();
		
		ProductSLAs = [SELECT ID FROM Product_SLA__c where Opportunity_Product__c in :OLISet];
		system.assertEquals (OLISet.size(),ProductSLAs.size(),'BatchProductSLARecalculationTest.testBatchProductSLARecalc: We expect Product SLAs to be created when batchProductSLARecalculation is called with custom settings');
	}
	
	
	
      public static void populateOLIRelatedData( integer numAccount, integer numOppPerAcct, integer numOLIperOpp) {
        // -- Accounts -- 
        system.debug('BatchProductSLARecalculationTest.populateOLIRelatedData: Creating 1 Accounts');       
         accounts = TestingUtils.createAccounts(numAccount,true);
        
        //  -- Opportunity Data --
        System.debug('BatchProductSLARecalculationTest.populateOLIRelatedData: Creating 1 Opportunities');  
        opportunities = new Opportunity[]{};   
        for (account a: accounts) {
             opportunities.addAll(TestingUtils.createOpportunities(numOppPerAcct,'TestProductSLAServicesOpp ' + a.name , a.Id, true));
        }
                
     // -- Opportunity Line Item, Proudct, & PriceBookEntry Data ---
        System.debug('BatchProductSLARecalculationTest.populateOLIRelatedData: Creating Product, Pricebook and PricebookEntry');           
        product = TestingUtils.createProduct('TestProductSLAServicesProduct',true);
        
          Pricebook2 pricebook = [select id from Pricebook2 where isStandard=true]; // Need to query this.  isStandard is not a writable field
                                                                                  // and we need a standard pricebook to insert another.
                                                                                  
        pricebookEntry = TestingUtils.createPriceBookEntry(product.Id, pricebook.Id, true);
       
        // Not calling the test util because we want to set the waiting status description here.          
        System.debug('BatchProductSLARecalculationTest.populateOLIRelatedData: Creating 5 opportunity products');           
        opportunityLineItems = new OpportunityLineItem[]{};
        for (Opportunity opp: opportunities) {
            for (integer i=0; i < numOLIperOpp; i++) {
                OpportunityLineItem OLI = TestingUtils.createOLI(pricebookEntry.ID, opp.Id, false);
                OLI.Waiting_Status_Descr__c = 'Test class insert'; 
                opportunityLineItems.add(OLI); 
        	}
        }
        insert opportunityLineItems; // This creates the Opportunity_Product_History__c
    }
    
    public static void createOppProdHist(boolean includeLive) {
        LastOutTime = datetime.now();
        // Inserts values from opportunityLineItem.Waiting_Status__c.  Any addtions to this pick list should be reflected here.
        map <integer, string> OLIStatus = new map <integer,string> {    0 => 'Created',
                                                                        1 => 'Closed Won',
                                                                        2 => 'Awaiting Onboard',
                                                                        3 => 'In Fulfillment',
                                                                        4 => 'Waiting On Client Approval',
                                                                        5 => 'Waiting On Client Resource',
                                                                        6 => 'Cancelled',
                                                                        7 => 'Pending',                                                                     
                                                                        8 => 'Paused:Billing',
                                                                        9 => 'Paused:No Contact',
                                                                        10 => 'Live',
                                                                        11 => 'Fulfilled Renewed',
                                                                        12 => 'Fulfilled Non-Renewal',
                                                                        13 => 'Fulfilled-Complete'
                                                                    }; 
                                                                            
       manualHistRecords = new Opportunity_Product_History__c[] {};
        // Create Opportunity Product History Logs manually.
        for (opportunityLineItem oli:opportunityLineItems) {
           manualHistRecords = TestingUtils.createOliHistory(9,false);//This makes sure every OLI has 9 associated records with the created           
        }
        for (opportunityLineItem OLI: opportunityLineItems) {
            for (integer i=1; i <  10; i++) {
                Opportunity_Product_History__c thisOppHist =  new Opportunity_Product_History__c();
                thisOppHist.Duration__c = 1.00;
                 thisOppHist.OLI_Product__c = OLI.Product2.ID;
                thisOppHist.OLI_Stage__c =  OLIStatus.get(i);
                thisOppHist.Opportunity__c =  OLI.Opportunity.ID;
                 thisOppHist.Opportunity_Product__c = string.valueof(OLI.ID);
                 thisOppHist.Time_In__c = LastOutTime;
                LastOutTime = LastOutTime.addHours(24);  //translates into 9 business hours, and 1 day.
                thisOppHist.Time_Out__c = LastOutTime;
                manualHistRecords.add(thisOppHist);
             }
        }
        insert manualHistRecords;
        OpportunityLineItemServices.processedOLIStatusChanges.clear();
         
        if (includeLive){
    		 opportunityLineItem[] OLIToUpdate = new opportunityLineItem[]{};
	         for (opportunityLineItem OLI: opportunityLineItems) {
	             OLI.Waiting_Status__c = 'Live';
	             OLI.Live_Date__c = LastOutTime.addHours(24);
	             OLIToUpdate.add(OLI);
	         }
	                
	        update OLIToUpdate;
	        OpportunityLineItemServices.processedOLIStatusChanges.clear();
            set<ID>OLISet = new map<ID,opportunityLineItem>(opportunityLineItems).keyset();
            ProductSLAs = [SELECT ID FROM Product_SLA__c where Opportunity_Product__c in :OLISet];
        }
    }

}