prod_snapshot_2015-09-24_1030/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Dig_Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dig - Account Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Digital_Fulfillment</fullName>
        <active>true</active>
        <businessProcess>SML Opportunity Process</businessProcess>
        <label>Digital Fulfillment</label>
    </recordTypes>
    <recordTypes>
        <fullName>USCP_Opportunity</fullName>
        <active>true</active>
        <businessProcess>USCP Opportunity Process</businessProcess>
        <description>USCP Opportunity</description>
        <label>USCP Opportunity</label>
    </recordTypes>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Affl_Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Affl Sales Rep</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Affiliated_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dig_Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dig Account Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Dig_AM_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Of_Service_Date__c</fullName>
        <label>End Of Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Has_ILI__c</fullName>
        <formula>Project__r.Has_ILI__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Has ILI&apos;S</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_ServiceEndDate__c</fullName>
        <label>Product End of Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_ServiceStartDate__c</fullName>
        <label>Product Start of Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Live_Date__c</fullName>
        <label>Live Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Live</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opp_Dig_Acct_Man_Id__c</fullName>
        <formula>Opportunity.Dig_Account_Manager__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opp Dig Acct Man Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opp_Owner_Id__c</fullName>
        <formula>Opportunity.OwnerId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opp Owner Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opp_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Rep_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Sales_Rep_Id__c</fullName>
        <formula>Opportunity.Sales_Rep__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opp Sales Rep Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Id__c</fullName>
        <formula>PricebookEntry.Product2.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Qty_ContractMonths__c</fullName>
        <label>Number of Contract Months</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <description>Opportunity Record type Name</description>
        <label>Record Type Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Change_Date__c</fullName>
        <label>Status Change Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Waiting_Status_Descr__c</fullName>
        <label>Status Descr/Notes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Waiting_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Onboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting On Client Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting On Client Resource</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hard Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Non-Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled-Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>--Internal Use Only--</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused:Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused:No Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Invoice_Frequency__c</fullName>
        <description>USCP Custom Field: Invoice Frequency</description>
        <label>Invoice Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Two Times</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Invoice_StatusToCreateILI__c</fullName>
        <label>Status to Create ILIs</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Affl_Sales_Rep__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Affl Sales Rep</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Has_ILI__c</fullName>
        <formula>Count_Of_ILI__c  &gt;= 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Has ILI&apos;S</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_ServiceEndDate__c</fullName>
        <label>Product End of Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_ServiceStartDate__c</fullName>
        <label>Product Start of Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Live_Date__c</fullName>
        <label>Live Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opp_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opp Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Id__c</fullName>
        <label>Product Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qty_ContractMonths__c</fullName>
        <label>Qty Contract Months</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Updates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/OpportunityLineItemBeforeUpdateHandler.cls
/**
 *  @Class Name : OpportunityLineItemBeforeUpdateHandler
    Created By  : Praneeth Kaleru
    Descritpion : To handler the Opportunity Line item before update operations
    Modifed By  : 03/03/2015 Refactored OpportunityLineItem Before Trigger Handler
 */
public class OpportunityLineItemBeforeUpdateHandler extends TriggerHandlerBase {
    
    public override void mainEntry(TriggerParameters tp) {
        this.setRecordTypeFlag(tp.newList);
        this.setOpportunityLineItemFieldsBeforeUpdate((Map<Id, OpportunityLineItem>)tp.oldMap, (Map<Id, OpportunityLineItem>)tp.newMap);
        this.updateOppLineItemProjectReference((Map<Id, OpportunityLineItem>)tp.oldMap, (Map<Id, OpportunityLineItem>)tp.newMap);
		this.updateOppLineItemInvoiceFields((Map<Id, OpportunityLineItem>)tp.oldMap, (Map<Id, OpportunityLineItem>)tp.newMap);
		//This will stop Opportunity Trigger Code execution from the updates in After Update OLI Trigger. make sure this is the last line
        VAlidator_BeforeOppProdUpdate_class.setAlreadyDone();
        
       
    }

	public override void inProgressEntry(TriggerParameters tp) {
		
	}
	
	/* 
                        ----------- BEGIN CODE TRANSPLANT -----------------
    */
	//set Opportunity Line Item Fields before update based on fields updates on dependent fields 
	private void setOpportunityLineItemFieldsBeforeUpdate(Map<Id, OpportunityLineItem> oldOpportunityLineItems, Map<Id, OpportunityLineItem> newOpportunityLineItems){
		//Getting Opportunity RecordType Id 
    	Set<Id> oppIds = new Set<Id>();
    	for(OpportunityLineItem oneOppLineItem : newOpportunityLineItems.Values()){
    		oppIds.add(oneOppLineItem.OpportunityId);
    	}
    	
    	Map<Id, Opportunity> mapOpportunities = new Map<Id, Opportunity>(
    												[Select Id, RecordTypeId from Opportunity Where Id IN: oppIds]
    											);
    	//Getting Opportunity RecordType Id 
    	
		//Loop through all Opp Line Items
		for(OpportunityLineItem oneOpportunityLineItem: newOpportunityLineItems.Values()){
			if (oneOpportunityLineItem.Live_Date__c != null && oneOpportunityLineItem.Quantity != null) {
				//Setting Field
				oneOpportunityLineItem.End_Of_Service_Date__c = oneOpportunityLineItem.Live_Date__c.date()
																		.addMonths(oneOpportunityLineItem.Quantity.intValue());
			}else if (oneOpportunityLineItem.Live_Date__c == null || oneOpportunityLineItem.Quantity == null){
				oneOpportunityLineItem.End_Of_Service_Date__c = null; //Setting Field
			}
		
			//If Logged in User is not same as Gannet Local User
			if (UserInfo.GetUserId() != Constants.GANNETT_LOCAL_USER.Id && !Validator_DigAMUpdate_class.hasDAMAlreadyDone()) {
				oneOpportunityLineItem.Opp_Owner__c = oneOpportunityLineItem.Opp_Owner_Id__c; //Setting Field
				oneOpportunityLineItem.Dig_Account_Manager__c = oneOpportunityLineItem.Opp_Dig_Acct_Man_Id__c; //Setting Field
				oneOpportunityLineItem.Affl_Sales_Rep__c = oneOpportunityLineItem.Opp_Sales_Rep_Id__c; //Setting Field
	
				if (oneOpportunityLineItem.Live__c == true && oldOpportunityLineItems.get(oneOpportunityLineItem.Id).Live__c == false) {
					oneOpportunityLineItem.Waiting_Status_Descr__c = null; //Setting Field
				}
				if (String.IsBlank(oneOpportunityLineItem.Waiting_Status__c) && oneOpportunityLineItem.Dig_Account_Manager__c != null
					 && mapOpportunities.get(oneOpportunityLineItem.OpportunityId).RecordTypeId != RecordTypeCache.getRecordType('Opportunity', 'USCP_Opportunity').Id){
					oneOpportunityLineItem.Waiting_Status__c = 'Awaiting OnBoard'; //Setting Field
				}
				if (oneOpportunityLineItem.Waiting_Status__c != oldOpportunityLineItems.get(oneOpportunityLineItem.Id).Waiting_Status__c) {
					oneOpportunityLineItem.Status_Change_Date__c = date.today(); //Setting Field
				}
			}
			
			//DEV-2800 FIP - Back fill Quantity field on OLI with Quantity of Contract months for USCP Opportunity
			if(mapOpportunities.get(oneOpportunityLineItem.OpportunityId).RecordTypeId == RecordTypeCache.getRecordType('Opportunity', 'USCP_Opportunity').Id){
				oneOpportunityLineItem.Quantity = oneOpportunityLineItem.Qty_ContractMonths__c;
			}
           		 // DEV 2966 Update the Start date with and End date based on the Live date
            		if(mapOpportunities.get(oneOpportunityLineItem.OpportunityId).RecordTypeId == RecordTypeCache.getRecordType('Opportunity', 'Digital_Fulfillment').Id 
               						&& oneOpportunityLineItem.Live_Date__c != null && oneOpportunityLineItem.Quantity != null)
            		{
                		oneOpportunityLineItem.End_Date__c = oneOpportunityLineItem.Live_Date__c.date()
																		.addMonths(oneOpportunityLineItem.Quantity.intValue());
                		oneOpportunityLineItem.ServiceDate = oneOpportunityLineItem.Live_Date__c.date();
			}
            
		}
	}
	
	//Update Opportunity Line Item with a reference to Project Object
	private void updateOppLineItemProjectReference(Map<Id, OpportunityLineItem> oldOpportunityLineItems, 
												   Map<Id, OpportunityLineItem> newOpportunityLineItems){
		Set<Id> oppLineItemIds = new set<Id>();										   	
		//If Logged in User is not same as Gannet Local User
		if (UserInfo.GetUserId() != Constants.GANNETT_LOCAL_USER.Id) {
			//Loop through all Opp Line Items
			for(OpportunityLineItem oneOpportunityLineItem: newOpportunityLineItems.Values()){
				if (oneOpportunityLineItem.Project__c == null) {
					oppLineItemIds.add(oneOpportunityLineItem.Id);
				}	
			}
			
			//Query for Project Objects based on Opp Line Item Ids
			if(oppLineItemIds.size()>0){
				List <Project__c> oppLineItemProjects = [Select Id, Product_Id__c from Project__c Where Product_Id__c in : oppLineItemIds];
				for (Project__c oneProject: oppLineItemProjects) {
					newOpportunityLineItems.get(oneProject.Product_Id__c).Project__c = oneProject.Id;
				}
			}
		}
	}
    // This method handles Product Start of Service Date & Product End of Service Date on OLI for USCP Opportunities based on different products.
    private void updateOppLineItemInvoiceFields(Map<Id, OpportunityLineItem> oldMap,
                                                Map<Id, OpportunityLineItem> newMap){ 
        map<Id, OpportunityLineItem> oliIdWithProductValues = new map<Id, OpportunityLineItem>();
        for(OpportunityLineItem oli : [SELECT Id, Invoice_ServiceEndDate__c, Invoice_ServiceStartDate__c, 
                                                Waiting_Status__c, Qty_ContractMonths__c, 
                                                PricebookEntry.Product2.Invoice_StatusToCreateILI__c,
                                                PricebookEntry.Product2.Invoice_Frequency__c
                                       FROM OpportunityLineItem
                                       WHERE Id In : newMap.keyset()
                                           AND Opportunity.RecordType.Name = 'USCP Opportunity']){
            oliIdWithProductValues.put(oli.Id, oli);    
        }
        for(OpportunityLineItem oli : newMap.values()){
            system.debug('********PricebookEntry.Product2.Invoice_StatusToCreateILI__c************'+oli.PricebookEntry.Product2.Invoice_StatusToCreateILI__c);
            if(oliIdWithProductValues.keyset().contains(oli.id)){
                if(oldMap.get(oli.id).Waiting_Status__c != oli.Waiting_Status__c 
                    && oli.Waiting_Status__c == oliIdWithProductValues.get(oli.Id).PricebookEntry.Product2.Invoice_StatusToCreateILI__c
                    && oliIdWithProductValues.get(oli.Id).PricebookEntry.Product2.Invoice_Frequency__c != 'Two Times'){
                    
                    if(oli.Invoice_ServiceStartDate__c == null && oli.Has_ILI__c == false){
                        oli.Invoice_ServiceStartDate__c = date.today();
                    }
                    
                    if(oli.Invoice_ServiceStartDate__c != null && oli.Has_ILI__c == false && oli.Waiting_Status__c != 'Closed Won'){
                        oli.Invoice_ServiceEndDate__c = ((oli.Invoice_ServiceStartDate__c).addMonths(Integer.valueOf(oli.Qty_ContractMonths__c))).adddays(-1);
                    }
                    
                    if(oli.Invoice_ServiceStartDate__c != null && oli.Has_ILI__c == false && oli.Waiting_Status__c == 'Closed Won'){
                        oli.Invoice_ServiceEndDate__c = oli.Invoice_ServiceStartDate__c;
                    }
                }
                
                if(oldMap.get(oli.id).Waiting_Status__c != oli.Waiting_Status__c
                    && oli.Waiting_Status__c == oliIdWithProductValues.get(oli.Id).PricebookEntry.Product2.Invoice_StatusToCreateILI__c 
                    && oliIdWithProductValues.get(oli.Id).PricebookEntry.Product2.Invoice_Frequency__c == 'Two Times'){
                    
                    if(oli.Invoice_ServiceStartDate__c == null && oli.Has_ILI__c == false)
                        oli.Invoice_ServiceStartDate__c = date.today();
                    
                    oli.Invoice_ServiceEndDate__c = null;
                } 
                
                if(oldMap.get(oli.id).Waiting_Status__c != oli.Waiting_Status__c
                    && oli.Waiting_Status__c == 'Fulfilled-Complete'
                    && oliIdWithProductValues.get(oli.Id).PricebookEntry.Product2.Invoice_Frequency__c == 'Two Times'){
                    
                    if(oli.Invoice_ServiceStartDate__c != null && oli.Invoice_ServiceEndDate__c == null)
                        oli.Invoice_ServiceEndDate__c = date.today();
                    
                } 
            }
        }
    }
	
	private void setRecordTypeFlag(List<OpportunityLineItem> newOpportunityLineItems)
    {
        Map<Id,RecordType> recMap = new Map<id,RecordType>([SELECT id,Name from RecordType where SobjectType = 'Opportunity']);
        Set<id> oppIdLst = new Set<id>();
        for(OpportunityLineItem oneOppLineItem : newOpportunityLineItems){
           oppIdLst.add(oneOppLineItem.opportunityid);
        }
        Map<id,Opportunity> oppMap = new Map<id,Opportunity>([select id,recordTypeid from opportunity where id =: oppIdLst]);
        for(OpportunityLineItem oneOppLineItem : newOpportunityLineItems)
        {
            Opportunity opp = oppMap.get(oneOppLineItem.opportunityid);
            if(recMap != null && opp.recordTypeid != null){ 
                oneOppLineItem.Record_Type_Name__c = recMap.get(opp.recordTypeid).name;
            }
        }
        
    }
}