prod_snapshot_2015-09-24_1030/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Invoice_ServiceEndDate__c</fullName>
        <label>Product End of Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_ServiceStartDate__c</fullName>
        <label>Product Start of Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Units__c</fullName>
        <formula>IF(NOT(ISBLANK(NumberOfHours__c)), NumberOfHours__c,  
   IF(NOT(ISBLANK(Email_Recipients_Qty__c)), Email_Recipients_Qty__c,
      IF(NOT(ISBLANK(NumberOfLocations__c)), NumberOfLocations__c,null
      )
   )
)</formula>
        <label>Invoice Units</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Live_Date__c</fullName>
        <label>Live Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Mgmt_Fee_Percent__c</fullName>
        <description>The Finance and Operations Teams need a way for the Jumpstart Team to code PPC Management Fee when it is put in as a product.</description>
        <label>Mgmt Fee %</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>160</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Form__c</fullName>
        <description>Order form link shows PPC Order Form for now and potentially be applied for any other products that requires a link</description>
        <formula>IF(AND( 
CONTAINS(PricebookEntry.Product2.ProductCode, &apos;SML-PPC Budgeted&apos;), 
ISPICKVAL(Opportunity.StageName, &apos;Closed Won&apos;), 
Opportunity.CloseDate &gt; DATE(2013,09,25)), 
HYPERLINK(&apos;apex/PPCOrderForm?OpportunityLineItemId=&apos; + Id, &apos;PPC Order Form&apos;, &apos;_parent&apos;) , &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order Form</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Periods2__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Periods/Cycles</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <formula>PricebookEntry.Product2.Description</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qty_ContractMonths__c</fullName>
        <label>Number of Contract Months</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell_Type__c</fullName>
        <label>Sell Type</label>
        <picklist>
            <picklistValues>
                <fullName>NewSell</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>UpSell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CrossSell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Extension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DownSell</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Waiting_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Onboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting On Client Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting On Client Resource</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hard Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Non-Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled-Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>--Internal Use Only--</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused:Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused:No Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/USCPOLIRelatedListCntrl.cls
public class USCPOLIRelatedListCntrl {
    Public List<OpportunityLineItem>  oliList {set;get;}
    Public Opportunity Opp {set;get;}
    Public string pricebkName {set;get;}
    private integer totalRecs {set;get;}
    private integer OffsetSize = 0;
    private integer LimitSize= 5;
    
    public ApexPages.StandardSetController con {
        get {
            if(con == null) {
                //String strSql = 'select id,Product2.name,Periods2__c,UnitPrice,ServiceDate,Product_Description__c,ListPrice,Opportunity.Pricebook2.Name from OpportunityLineItem where opportunityid =\'' +opp.id+'\'';
        
                con = new ApexPages.StandardSetController(Database.getQueryLocator(
                      [select id,name,(select id,Product2.name,Notes__c,Sell_Type__c,Qty_ContractMonths__c,Invoice_Units__c,Mgmt_Fee_Percent__c,Quantity,UnitPrice,Invoice_ServiceStartDate__c,Invoice_ServiceEndDate__c,Waiting_Status__c,Live_Date__c,ListPrice,Opportunity.Pricebook2.Name,Order_Form__c,Opportunity.CloseDate,PricebookEntry.Product2.ProductCode,Opportunity.StageName from OpportunityLineItems) from opportunity where id = :opp.id]));
            }
            return con;
        }
        set;
    }
    
    public USCPOLIRelatedListCntrl(ApexPages.StandardController stdController) {
        
         Opp = (Opportunity)stdController.getRecord(); 
       Opportunity opb1 = [select id,Pricebook2.Name from Opportunity where id =:opp.id ]; 
        totalRecs = [select count() from OpportunityLineItem where opportunityid = :opp.id];
       oliList =  [select id,Product2.name,Notes__c,Sell_Type__c,Qty_ContractMonths__c,Invoice_Units__c,Mgmt_Fee_Percent__c,Quantity,UnitPrice,Invoice_ServiceStartDate__c,Invoice_ServiceEndDate__c,Live_Date__c,ListPrice,Opportunity.Pricebook2.Name,Order_Form__c,Opportunity.CloseDate,PricebookEntry.Product2.ProductCode,Opportunity.StageName,Waiting_Status__c from OpportunityLineItem where opportunityid = :opp.id LIMIT :LimitSize OFFSET :OffsetSize];
       //totalRecs = oliList.size();
       pricebkname = opb1.Pricebook2.Name; 
    }
    public void createQueryString()
    {
        oliList =  [select id,Product2.name,Notes__c,Sell_Type__c,Qty_ContractMonths__c,Invoice_Units__c,Mgmt_Fee_Percent__c,Quantity,UnitPrice,Invoice_ServiceStartDate__c,Invoice_ServiceEndDate__c,Live_Date__c,ListPrice,Opportunity.Pricebook2.Name,Order_Form__c,Opportunity.CloseDate,PricebookEntry.Product2.ProductCode,Opportunity.StageName,Waiting_Status__c from OpportunityLineItem where opportunityid = :opp.id LIMIT :LimitSize OFFSET :OffsetSize];
        
        
    }
    //Pagination
    public void FirstPage()
    {
        OffsetSize = 0;
        createQueryString();
        
    }
    public void previous()
    {
       OffsetSize = OffsetSize-LimitSize;
        createQueryString();
        
    }
    public void next()
    {
        
        OffsetSize = OffsetSize + LimitSize;
        createQueryString();
        
    }
     public integer pageNumber {
        get {
            integer pageNo=1;
             pageNo = pageNo + (OffsetSize/LimitSize);
           
            return pageNo;
        }
        set;
    }
    public integer totalPages {
        get {
            integer totlPages=0;
            if(math.mod(totalRecs,LimitSize) > 0)
                {totlPages = totlPages + (totalRecs/LimitSize)+1;
                system.debug('total pages-------'+totlPages);
                system.debug('total Records-------'+totalRecs);}
            else
                totlPages = totlPages + (totalRecs/LimitSize);
            
             
        
           // return con.getPageNumber();
            return totlPages;
        }
        set;
    }
    public void LastPage()
    {
        
        OffsetSize = totalrecs-math.mod(totalRecs,LimitSize)-1;
        createQueryString();
    }
    public boolean getprev()
    {
        if(OffsetSize == 0 || totalRecs==5)
            return false;
        else
            return true;
    }
    public boolean getnxt()
    {
        if((OffsetSize + LimitSize) > (totalRecs-1))
            return false;
        else
            return true;
    }
    
    Public PageReference addProduct()
    {
        PageReference ref = new PageReference('/apex/OpportunityPriceBook?oppId='+opp.id);
        //ref.getParemeters().put('inline','0');
        //ref.setRedirect(true);
        system.debug('Add products Page::'+ ref);
        return ref;
    }
    public PageReference oliDelete()
    {
        String oliId = ApexPages.currentPage().getParameters().get('oliid');
        PageReference ref = new PageReference('/'+opp.id);
        ref.setRedirect(true);
        OpportunityLineItem oli = new OpportunityLineItem(id=oliId);
        delete oli;
        
        return ref;
    }
}