prod_snapshot_2015-09-24_1030/objects/Opportunity_Product_History__c.object
<CustomObject>
    <description>History object used to track status changes in Opportunity Products</description>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>OLI_Stage__c</fullName>
        <label>OLI Stage</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Product__c</fullName>
        <label>Opportunity Product</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Product Histories</relationshipLabel>
        <relationshipName>Opportunity_Product_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_In__c</fullName>
        <label>Time_In</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Time_Out__c</fullName>
        <label>Time Out</label>
        <type>DateTime</type>
    </fields>
    <label>Opportunity Product History</label>
    <nameField>
        <displayFormat>SLA-{00000000}</displayFormat>
        <label>Opportunity Product History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/OLIStatusHistoryCompCntrl.cls
/*OLI Status History Component Controller*/
public class OLIStatusHistoryCompCntrl {
public id oliId {set;get;}
 public List<OpportunityLineItemChartServices.OppProductHistoryRecord> historyTrackRecords = null;

 public OLIStatusHistoryCompCntrl()
 {
     this.HistoryTrackRecords = new List<OpportunityLineItemChartServices.OppProductHistoryRecord>();
          
    
     
 }
   
   public List<OpportunityLineItemChartServices.OppProductHistoryRecord>  getHistoryTrackRecords()
   {
      List<Opportunity_Product_History__c> HistoryTrack = [Select     Id, 
                                        Opportunity__c, 
                                        Opportunity_Product__c, 
                                        OLI_Stage__c, 
                                        Notes__c,
                                        Duration__c, 
                                        Time_In__c, 
                                        Time_Out__c,
                                        CreatedBy.Name,
                                        LastModifiedBy.Name
                            From Opportunity_Product_History__c 
                            Where Opportunity_Product__c = :oliId 
                            Order By Time_In__c];
       Integer i = 0;
      system.debug('oliId::'+oliId);
     system.debug('prod history::'+HistoryTrack);
       for (Opportunity_Product_History__c oppProdHist : HistoryTrack){
           OpportunityLineItemChartServices.OppProductHistoryRecord hRecord = new OpportunityLineItemChartServices.OppProductHistoryRecord(oppProdHist);
            hRecord.orderOfOccurence = ++i;
           HistoryTrackRecords.add(hRecord);  
           
       } 
       return HistoryTrackRecords;
       
   }
    
}