prod_snapshot_2015-09-24_1030/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>OriginalValueSetBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Value Set By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OppOriginalValueSetBy</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OriginalValueSetDate__c</fullName>
        <label>Original Value Set Date</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Product_CurrentValue__c</fullName>
        <formula>IF(AND(NOT(ISBLANK(Record_Type_Name__c)),Record_Type_Name__c == &apos;USCP Opportunity&apos;), TotalPrice + (TotalPrice * Mgmt_Fee_Percent__c), ( Quantity * UnitPrice )+ HTML_Fee__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Product Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_OriginalValue__c</fullName>
        <label>Original Product Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Waiting_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Onboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting On Client Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting On Client Resource</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hard Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Non-Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled-Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>--Internal Use Only--</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused:Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused:No Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/ContractOriginalValue.cls
global with sharing class ContractOriginalValue{

    webservice static string setSingleOriginalContractValue(ID oppID)
    {
        string ErrorMessage ='Success';
        Opportunity opp = new Opportunity();
        try 
        {
            opp = [SELECT   ID, 
                                        StageName, 
                                        OriginalValueSetDate__c,
                                        OriginalValueSetBy__c
                                   FROM Opportunity 
                                   WHERE ID = :oppID];
                               
            OpportunityLineItem[] oliList = [SELECT   ID,
                                                    Product_CurrentValue__c,
                                                    Product_OriginalValue__c,
                                                    Waiting_Status__c
                                           FROM OpportunityLineItem
                                           WHERE OpportunityID = :oppID
                                           AND Waiting_Status__c IN ('','Closed Won')];
            //Ensure it has OLIs associated to it
            if (!oliList.isEmpty())
            {
                // Original Value not set earlier
                if (opp.OriginalValueSetDate__c == null)
                {
                    // Opportunity in the right stages
                    if ((opp.StageName == 'Closed Won' || opp.StageName == 'Contract Approved' || opp.StageName == 'Contract Approved by Jumpstart'))
                    {
                        // Set timestamps on Opporunity
                        opp.StageName = 'Closed Won'; 
                        opp.OriginalValueSetDate__c = datetime.now();
                        opp.OriginalValueSetBy__c = UserInfo.getUserId();
                        update opp;
                        
                        //Update the OLI Product_OriginalValue__c to Product_CurrentValue__c
                        for (integer i = 0; i < oliList.size(); i++)        
                        {
                            oliList[i].Product_OriginalValue__c = oliList[i].Product_CurrentValue__c;
                        }
                        update oliList;

                       
                    } // End if opportunity in the right stages
                    else 
                    {
                        ErrorMessage = 'The Opportunity\'s original contract values and stage may not be calculated and updated if the stage is not \"Contract Approved\" or \"Closed Won\". Please contact a Finance Manager to proceed.';
                    } // End wrong opp stages
                } // End If Original Value not set earlier
                else
                {
                    ErrorMessage = 'The Opportunity\'s original contract values have already been calculated.';
                }// Original Value set earlier
            }//End if has related OLI
            else
            {
                ErrorMessage = 'No eligible Opportunity Products found to calculate Original Values for.  Please ensure there are opportunity products assoicated, and their status\' are in \'Closed Won\' or are blank.';
            }// end no related OLI
        }
        catch(exception ex)
        {
            ErrorMessage = ex.getMessage();
        }
        return ErrorMessage;
    }
}