prod_snapshot_2015-09-24_1030/objects/Opportunity_Product_History__c.object
<CustomObject>
    <description>History object used to track status changes in Opportunity Products</description>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OLI_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OLI Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunity Product Histories</relationshipLabel>
        <relationshipName>Opportunity_Product_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OLI_Stage__c</fullName>
        <label>OLI Stage</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Product_Type__c</fullName>
        <description>Type of product</description>
        <label>Opportunity Product Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Product__c</fullName>
        <label>Opportunity Product</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Product Histories</relationshipLabel>
        <relationshipName>Opportunity_Product_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Days_To_Go_Live__c</fullName>
        <label>Product Days To Go Live</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Live_Date__c</fullName>
        <label>Product Live Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Time_In__c</fullName>
        <label>Time_In</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Time_Out__c</fullName>
        <label>Time Out</label>
        <type>DateTime</type>
    </fields>
    <label>Opportunity Product History</label>
    <nameField>
        <displayFormat>SLA-{00000000}</displayFormat>
        <label>Opportunity Product History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Days_To_Go_Live__c</fullName>
        <formula>if( ISNULL( Live_Date__c ),null,   DATEVALUE(Live_Date__c ) -DATEVALUE( Opportunity.Closed_Won_Time_Stamp__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label># Days To Go Live</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Live_Date__c</fullName>
        <label>Live Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Waiting_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Onboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting On Client Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting On Client Resource</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hard Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled Non-Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled-Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>--Internal Use Only--</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused:Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused:No Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Accessories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Art</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back to school</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bedding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car accessories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clothing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cookware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facebook Ads</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housewares</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>iPhone accessories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jewelry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile-Only Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outdoor supplies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pet Supplies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retargeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Ads</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Media Mgmt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Template Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toys</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Website</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

prod_snapshot_2015-09-24_1030/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Live_Date__c</fullName>
        <label>Live Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Updates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/TestOpportunityLineItemTrigger.cls
@isTest(seeAllData=true)

public class TestOpportunityLineItemTrigger {
	
	final static String OPP_STAGE_NAME_1 = 'Book Appointment';
	final static String OPP_STAGE_NAME_2 = 'Pitched';
	final static String OPP_STAGE_NAME_3 = 'Contract Sent';
	final static String OPP_STAGE_NAME_4 = 'Contract Won';
	final static String OPP_STAGE_NAME_5 = 'Contract Lost';
	final static String OLI_WAITING_STATUS_1 = 'Awaiting Onboard';
	final static String OLI_WAITING_STATUS_2 = 'In Fulfillment';
	final static String OLI_WAITING_STATUS_3 = 'Waiting On Client Approval';
	final static String OLI_WAITING_STATUS_4 = 'Waiting On Client Resource';
	final static String OLI_WAITING_STATUS_5 = 'Live';
	final static String OLI_WAITING_STATUS_6 = 'Canceled';
	final static String OLI_WAITING_STATUS_7 = 'Pending';
	final static String OLI_WAITING_STATUS_8 = 'Fulfilled Renewed';
	final static String OLI_WAITING_STATUS_9 = 'Fulfilled Non-Renewal';
	final static String OLI_WAITING_STATUS_10 = 'Fulfilled-Complete';
	final static String OLI_WAITING_STATUS_11 = '--Internal Use Only--';
	final static String OLI_WAITING_STATUS_12 = 'Paused:Billing';
	final static String OLI_WAITING_STATUS_13 = 'Paused:No Contact';
	
	public static List<Opportunity_Product_History__c> getOppProductHistories(Id oliId){
		List<Opportunity_Product_History__c> actualOppProductHistories = [Select Id, Time_Out__c, Time_In__c, OLI_Project__c,
																				Opportunity_Product__c,Opportunity__c,
																				Duration__c,OLI_Stage__c, Opportunity_Product_Type__c, 
																				Product_Days_To_Go_Live__c, Product_Live_Date__c
																		  		From Opportunity_Product_History__c Where Opportunity_Product__c = :oliId];
		return actualOppProductHistories;
	}
	
	public testmethod static void testOpportunityLineItemInsert(){
		// new OLI History object created with time_in as created date and no time_out
		
		final Integer NUM_EXPECTED_OPP_PROD_HISTORY = 1;
		
		Account testAccount = TestingUtils.createAccounts(1, true)[0];
		Opportunity testOpp = TestingUtils.createOpportunities(1, 'test opp', testAccount.Id, false)[0];
		testOpp.StageName = OPP_STAGE_NAME_1;
		testOpp.CloseDate = Date.today().addDays(1);
		insert testOpp;
		Pricebook2 testStandardPriceBook = [select id from Pricebook2 where IsStandard = true];
		Product2 testProd = TestingUtils.createProduct('test prod', true);
		PriceBookEntry testPbe = TestingUtils.createPriceBookEntry(testProd.Id, testStandardPriceBook.Id, true);
		
		OpportunityLineItem testOLI = TestingUtils.createOLIandGetRecordInfo(testPbe.Id, testOpp.Id, false);

		Test.startTest();
			insert testOLI;
		Test.stopTest();
		
		List<Opportunity_Product_History__c> actualOppProdHistories = getOppProductHistories(testOLI.Id);
		System.assertEquals(NUM_EXPECTED_OPP_PROD_HISTORY, actualOppProdHistories.size(), 'We expect to get back the correct number of Opportunity Product History objects for each New Opportunity Line Item');
		System.assertEquals(testOpp.Id, actualOppProdHistories[0].Opportunity__c, 'We expect to get back the correct Opportunity for each Opportunity Product History');
		System.assertEquals(testOLI.Id, actualOppProdHistories[0].Opportunity_Product__c, 'We expect to get back the correct Opportunity Product for each Opportunity Product History');
		System.assertEquals(testOLI.Project__c, actualOppProdHistories[0].OLI_Project__c, 'We expect to get back the correct OLI Project for each Opportunity Product History');
		System.assertEquals(testOLI.Days_To_Go_Live__c , actualOppProdHistories[0].Product_Days_To_Go_Live__c, 'We expect to get back the correct days to live for the first Opportunity Product History record');
		System.assertEquals(testOLI.Live_Date__c , actualOppProdHistories[0].Product_Live_Date__c, 'We expect to get back the correct live date for the first Opportunity Product History record');
		System.assertEquals(OpportunityLineItemServices.CREATED_STAGE_NAME, actualOppProdHistories[0].OLI_Stage__c, 'We expect to get back the correct OLI Stage for each Opportunity Product History');
		
	}
	
	public testMethod static void testOpportunityLineItemInsertWithProductType(){
		
		final Integer NUM_EXPECTED_OPP_PROD_HISTORY = 1;
		final String  EXPECTED_OPP_PROD_TYPE = 'Social';
		
		Account testAccount = TestingUtils.createAccounts(1, true)[0];
		Opportunity testOpp = TestingUtils.createOpportunities(1, 'test opp', testAccount.Id, false)[0];
		testOpp.StageName = OPP_STAGE_NAME_1;
		testOpp.CloseDate = Date.today().addDays(1);
		insert testOpp;
		Pricebook2 testStandardPriceBook = [select id from Pricebook2 where IsStandard = true];
		Product2 testProd = TestingUtils.createProduct('test prod', false);
		testProd.Product_Type__c = EXPECTED_OPP_PROD_TYPE;
		insert testProd;
		PriceBookEntry testPbe = TestingUtils.createPriceBookEntry(testProd.Id, testStandardPriceBook.Id, true);
		
		OpportunityLineItem testOLI = TestingUtils.createOLIandGetRecordInfo(testPbe.Id, testOpp.Id, false);

		Test.startTest();
			insert testOLI;
		Test.stopTest();
		
		List<Opportunity_Product_History__c> actualOppProdHistories = getOppProductHistories(testOLI.Id);
		System.assertEquals(NUM_EXPECTED_OPP_PROD_HISTORY, actualOppProdHistories.size(), 'We expect to get back the correct number of Opportunity Product History objects for each New Opportunity Line Item');
		System.assertEquals(testOpp.Id, actualOppProdHistories[0].Opportunity__c, 'We expect to get back the correct Opportunity for each Opportunity Product History');
		System.assertEquals(testOLI.Id, actualOppProdHistories[0].Opportunity_Product__c, 'We expect to get back the correct Opportunity Product for each Opportunity Product History');
		//System.assertEquals(testOLI.Project__c, actualOppProdHistories[0].OLI_Project__c, 'We expect to get back the correct OLI Project for each Opportunity Product History');
		System.assertEquals(testOLI.Days_To_Go_Live__c , actualOppProdHistories[0].Product_Days_To_Go_Live__c, 'We expect to get back the correct days to live for the first Opportunity Product History record');
		System.assertEquals(testOLI.Live_Date__c , actualOppProdHistories[0].Product_Live_Date__c, 'We expect to get back the correct live date for the first Opportunity Product History record');
		//System.assertEquals(EXPECTED_OPP_PROD_TYPE, actualOppProdHistories[0].Opportunity_Product_Type__c, 'We expect to get back the correct Opportunity Product Type for each Opportunity Product History');
		System.assertEquals(OpportunityLineItemServices.CREATED_STAGE_NAME, actualOppProdHistories[0].OLI_Stage__c, 'We expect to get back the correct OLI Stage for each Opportunity Product History');
		
	}

	public testmethod static void testOpportunityLineItemUpdateNoStatusChange(){
		// no new OLI History objects
		
		final Integer NUM_EXPECTED_OPP_PROD_HISTORY = 1;
		
		Account testAccount = TestingUtils.createAccounts(1, true)[0];
		Opportunity testOpp = TestingUtils.createOpportunities(1, 'test opp', testAccount.Id, false)[0];
		testOpp.StageName = OPP_STAGE_NAME_1;
		testOpp.CloseDate = Date.today().addDays(1);
		insert testOpp;
		Pricebook2 testStandardPriceBook = [select id from Pricebook2 where IsStandard = true];
		Product2 testProd = TestingUtils.createProduct('test prod', true);
		PriceBookEntry testPbe = TestingUtils.createPriceBookEntry(testProd.Id, testStandardPriceBook.Id, true);
		
		OpportunityLineItem testOLI = TestingUtils.createOLIandGetRecordInfo(testPbe.Id, testOpp.Id, true); 
		
		Datetime OPP_PROD_1_TIME_IN = testOLI.LastModifiedDate.date();
		Datetime OPP_PROD_1_TIME_OUT = null; 
		
		testOLI.ServiceDate = Date.today().addDays(2); 
		
		Test.startTest();
			update testOLI;
		Test.stopTest();

		List<Opportunity_Product_History__c> actualOppProdHistories = getOppProductHistories(testOLI.Id); 
		System.assertEquals(NUM_EXPECTED_OPP_PROD_HISTORY, actualOppProdHistories.size(), 'We expect to get back the correct number of Opportunity Product History objects for each New Opportunity Line Item');
		System.assertEquals(testOpp.Id, actualOppProdHistories[0].Opportunity__c, 'We expect to get back the correct Opportunity for each Opportunity Product History');
		System.assertEquals(testOLI.Id, actualOppProdHistories[0].Opportunity_Product__c, 'We expect to get back the correct Opportunity Product for each Opportunity Product History');
		System.assertEquals(OPP_PROD_1_TIME_IN, actualOppProdHistories[0].Time_In__c.date(), 'We expect to get back the correct date/time of Time In for the first Opportunity Product History record');
		System.assertEquals(OPP_PROD_1_TIME_OUT, actualOppProdHistories[0].Time_Out__c, 'We expect to get back the correct date/time of Time Out for the first Opportunity Product History record');
		
		
	}
	
	public testmethod static void testOpportunityLineItemUpdateWithStatusChange(){
		// new OLI History objects created with latest record time_out updated
		
		final Integer NUM_EXPECTED_OPP_PROD_HISTORY = 2;
		
		Account testAccount = TestingUtils.createAccounts(1, true)[0];
		Opportunity testOpp = TestingUtils.createOpportunities(1, 'test opp', testAccount.Id, false)[0];
		testOpp.StageName = OPP_STAGE_NAME_1;
		testOpp.CloseDate = Date.today().addDays(1);
		insert testOpp;
		Pricebook2 testStandardPriceBook = [select id from Pricebook2 where IsStandard = true];
		Product2 testProd = TestingUtils.createProduct('test prod', true);
		PriceBookEntry testPbe = TestingUtils.createPriceBookEntry(testProd.Id, testStandardPriceBook.Id, true);
		
		OpportunityLineItem testOLI = TestingUtils.createOLIandGetRecordInfo(testPbe.Id, testOpp.Id, true); 
		Date OPP_PROD_1_TIME_IN = testOLI.CreatedDate.date();
		testOLI.ServiceDate = Date.today().addDays(2);
		testOLI.Waiting_Status__c = OLI_WAITING_STATUS_2;
		
		Test.startTest();
			OpportunityLineItemServices.processedOLIStatusChanges.remove(testOLI.ID);// trigger should process an ID only once per execution block
			// OpportunityLineItemServices.firstRun = true; // trigger should not run twice in same block of execution
			update testOLI;
		Test.stopTest();
		Map<Id, OpportunityLineItem> mapOppLineItems = new Map<Id, OpportunityLineItem>([Select Id, Project__c, LastModifiedDate
																		From OpportunityLineItem Where Id =: TestOLI.Id]);
		String OPP_PROD_PROJECT = mapOppLineItems.get(TestOLI.Id).Project__c;
		Date OPP_PROD_1_TIME_OUT = mapOppLineItems.get(TestOLI.Id).LastModifiedDate.date();
		Date OPP_PROD_2_TIME_IN = mapOppLineItems.get(TestOLI.Id).LastModifiedDate.date();

		List<Opportunity_Product_History__c> actualOppProdHistories = getOppProductHistories(testOLI.Id);

		System.assertEquals(NUM_EXPECTED_OPP_PROD_HISTORY, actualOppProdHistories.size(), 'We expect to get back the correct number of Opportunity Product History objects for each New Opportunity Line Item');
		for (Opportunity_Product_History__c oppProdHist : actualOppProdHistories){
			System.assertEquals(testOpp.Id, oppProdHist.Opportunity__c, 'We expect to get back the correct Opportunity for each Opportunity Product History');
			System.assertEquals(testOLI.Id, oppProdHist.Opportunity_Product__c, 'We expect to get back the correct Opportunity Product for each Opportunity Product History');
			System.assertEquals(OPP_PROD_PROJECT, oppProdHist.OLI_Project__c, 'We expect to get back the correct OLI Project for each Opportunity Product History');
			System.assertEquals(testOLI.Days_To_Go_Live__c , oppProdHist.Product_Days_To_Go_Live__c, 'We expect to get back the correct days to live for the first Opportunity Product History record');
			System.assertEquals(testOLI.Live_Date__c , oppProdHist.Product_Live_Date__c, 'We expect to get back the correct live date for the first Opportunity Product History record');
		
		}
		System.assertEquals(OPP_PROD_1_TIME_IN, actualOppProdHistories[0].Time_In__c.date(), 'We expect to get back the created date of the opportunity product as the Time In of the first Opportunity Product History record');
		System.assertEquals(OPP_PROD_1_TIME_OUT, actualOppProdHistories[0].Time_Out__c.date(), 'We expect to get back the last modified date of the opportunity product as the Time Out of the first Opportunity Product History record');
		System.assertEquals(OPP_PROD_2_TIME_IN, actualOppProdHistories[1].Time_In__c.date(), 'We expect to get back the last modified date of the opportunity product as the Time In of the latest Opportunity Product History record');
		System.assertEquals(null, actualOppProdHistories[1].Time_Out__c, 'We expect to get back the last modified date of the opportunity product as the Time Out of the latest Opportunity Product History record');
		
	}
	
	public testmethod static void testOpportunityLineItemDelete(){
		// all related OLI History objects deleted
		
		final Integer NUM_EXPECTED_OPP_PROD_HISTORY = 0;
		
		Account testAccount = TestingUtils.createAccounts(1, true)[0];
		Opportunity testOpp = TestingUtils.createOpportunities(1, 'test opp', testAccount.Id, false)[0];
		testOpp.StageName = OPP_STAGE_NAME_1;
		testOpp.CloseDate = Date.today().addDays(1);
		insert testOpp;
		Pricebook2 testStandardPriceBook = [select id from Pricebook2 where IsStandard = true];
		Product2 testProd = TestingUtils.createProduct('test prod', true);
		PriceBookEntry testPbe = TestingUtils.createPriceBookEntry(testProd.Id, testStandardPriceBook.Id, true);
		
		OpportunityLineItem testOLI = TestingUtils.createOLI(testPbe.Id, testOpp.Id, true);
		// assume OpportunityProductHistory record created : as tested in testOpportunityLineItemInsert()
		Test.startTest();
			OpportunityLineItemServices.processedOLIStatusChanges.remove(testOLI.ID);// trigger should process an ID only once per execution block
			//OpportunityLineItemServices.firstRun = true; // trigger should not run twice in same block of execution
			delete testOLI;
		Test.stopTest();
		
		List<Opportunity_Product_History__c> actualOppProdHistories = getOppProductHistories(testOLI.Id);
		System.assertEquals(NUM_EXPECTED_OPP_PROD_HISTORY, actualOppProdHistories.size(), 'We expect to get back no Opportunity Product History records for each deleted Opportunity Line Item');
	}
	
}