prod_snapshot_2015-09-24_1030/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Product_Id__c</fullName>
        <label>Product Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Updates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prod_snapshot_2015-09-24_1030/classes/processBuilder_InsertInvoiceLineItems.cls
/* This class will be invoked from process builder
    This class handles the insertion of Invoive Line items
*/

public class processBuilder_InsertInvoiceLineItems{
  
    @InvocableMethod
    public static void insertInvoiceLineItems(List<Project__c> proj){
        if(proj != null && proj.size()>0){
            
            map<Id, Id> oliIdWithProjectMap = new  map<Id, Id>();
            for(Project__c proObj : proj){
                
                oliIdWithProjectMap .put(proObj.Product_Id__c, proObj.Id);
                
            }
            
            USCPILIGenerator iliGenerator = new USCPILIGenerator ();
            iliGenerator.insertInvoiceLineItems(oliIdWithProjectMap);
        }
    }
}